:userdoc.
:prolog.
:docprof hyphen=yes justify=yes layout=1 tipage=center.
:docprof toc='*5' style=cemb duplex=yes ldrdots=yes screen=shade.
:title stitle='C for Embedded Systems'.
:library.An Easy Approach:
:topic.C for Embedded Systems
:etitle.
:docnum.3040-3050-99
:partnum.3040-99
:filenum.CEMB
:prtloc.Printed in Auburn
:date.April 28, 2026
:author.Evie Cooper
.nameeps cmstype=eps pdsfull='wec.doc.eps'
:artdef id=cynthia name=vgcynthi align=center.
:artdef id=clogo name=clogo align=center.
:eprolog.
:frontm.
:tipage.
.config coverpg on
.when 'usecyn' insert
:cover artid=cynthia.
.when 'not usecyn' insert
:cover artid=clogo.
.config coverpg off
:notices.
This is the textbook for the ELEC 3040/3050 (Embedded Systems Design
Lab) class.
 
Students are expected to have at least been introduced to the concepts
in this book in ELEC 2220 (Computer Systems) before reading this book.
 
No generative AI (ChatGPT, Gemini, Claude, etc) was used in the
production of this book.
 
Thank you Dr. Brown, Dr. Nelson, and Dr. Nelms for their feedback during the composition of this book!
:enotices.
:vnotice.
:vnhd.First Edition, Fall 20226
:note.While this is intended to be a generic :q.C for embedded systems 
primer,:eq. this book is :hp1.heavily:ehp1. targeted towards being a 
reference that is easily flipped through! Use the retrieval key at the 
top of each page, or the subject at the bottom  right of every page to 
find things quickly!
:coprnote.&copr. Evie Cooper 2026
:coprext.For corrections or comments, please email 
:pv.wec0007@auburn.edu:epv.!
:evnotice.
:preface.Preface
:p.Often times, people hear about C and don't fully understand what all 
it entails. C is a very :hp1.unusual:ehp1. language in the sense that 
it's not well-suited for the writing of large applications (like, for 
example, a web browser or a word processor like Microsoft Word) and is 
more suited for core system programs and firmware.
:p.In the past when early computers were large, they were almost 
universally programmed in some form of :hp5.assembly language:ehp5., 
but writing entire large applications in assembler proved to be rather 
unwieldily.
As a result, the mainframe-era assembler programmers employed tons of 
helpful :hp1.macros:ehp1. to gradually relieve the typing requirements 
of writing plain assembler code.
:p.When C was designed in the 1970s, it was intended to provide :q.one 
step above assembler language:eq. and strike a balance between 
assembler and a proper high-level language (which, in those days, were 
languages like FORTRAN for math, COBOL for business applications, PL/I 
for user applications, and a whole assortment of now-forgotten 
languages for which C is used now).
:p.C originated from the :hp1.UNIX operating system:ehp1. and was 
intended to be low-level enough that one could write machine-specific 
code in C, but also write full applications like a text editor in it!
The UNIX authors wanted to run their operating system on a variety of 
computers with distinctly :hp1.different:ehp1. processors -- naturally, 
these processors all used different assembler languages as they all 
used different instruction-set architectures.
:fn.The :hp2.ISA:ehp2. is a topic introduced in ELEC 2220 and covered 
in great detail in the ELEC 5200/6200 Operating Systems course, but the 
short summary is this: the ISA defines the CPU registers and the CPU 
instructions (and, therefore, the way the assembler language looks).
:efn.
:p.As such, in this book, we will be examining C as a :hp2.high-level 
assembly language:ehp2. of sorts; the low-level configuration commands 
used on an STMicroelectronics STM32 will not work on an Atmel AVR or 
any other microcontroller.
:fn.The Arduino line used to use AVRs heavily, but now includes other 
CPU architectures thanks to high-level wrapper libraries like 
:pv.Wiring:epv..
:efn.
Think of this like writing assembler programs with less typing!
:p.Throughout this book, the following typing conventions will be used:
:ul.
:li.Program/variable/library name:
:p.:pv.libc.a:epv.
:li.Program keyword/function name:
:p.:pk.switch:epk.
:li.Source code:
:xmp.int main()
:exmp.
:li.Key program function or idea:
:p.:hp3.Debugging:ehp3.
:li.Vocabulary word:
:p.:hp2.3040/3050:ehp2.
:li.Emphasis:
:p.:hp1.Embedded:ehp1.
:p.:hp5.Lab:ehp5.
:li.Button:
:p.:rk.Run:erk. 
:eul.
:p.This document was formatted with IBM BookMaster 1.4 and DCF/SCRIPT 
1.4; the images were prepared with :pv.ADMDRAW:epv. (a custom-written 
VM/CMS vector artwork program); artwork was prepared with Inkscape 
1.4.4; the text was edited with Mike Cowlishaw's LEXX; the HTML version 
of this document was formatted with AT&T :pv.B2H:epv.. 
:p.There are no raster images in this document unless you are viewing 
the HTML version of this, wherein all of the images are in GIF format. 
:p.Thank you Dr. Brown, Dr. Nelson, and Dr. Nelms for their feedback 
during the composition of this book!
:toc.
:figlist.
:tlist.
:body.
:h0.Introduction
:p.This section will provide some background information on the C 
language and the environment in which your programs will run.
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3. Whenever you see this icon, read this section. Sections 
not prefixed by this are less important for ELEC 3040/3050, but are 
useful to know nevertheless.
:h1 id=environ.Understanding the C Environment
:p.Before getting carried away writing programs, it is helpful to 
understand the environment in which your programs are written and run.
In the olden days, one would just execute a command to run the C 
compiler (since, likewise, in those olden days, computers were 
command-line-based systems where you would just type in the name of a 
program you want to run on a command prompt) like :pk.cc:epk. on UNIX, 
:pk.cl:epk. on MS-DOS, so on and so forth; nowadays, we just click the 
Run button and it somehow works!
:h2.Compilation Process
:p.However, it is :hp1.definitely:ehp1. helpful to understand what goes 
on under the hood! When you click that Run (or Debug) button, the 
following programs run in quick succession:
:ol.
:li.:hp2.Preprocessor::ehp2. this program resolves the 
:hp1.preprocessor directives:ehp1. found in the program, like:
:i1.Preprocessor
:ul.
:li.File inclusions
:li.Macros
:li.Conditional compilation
:eul.
:li.:hp2.Compiler::ehp2. this program will take the preprocessed source 
code, then employ a technique that will translate the C into assembler 
language. As such, the target CPU must be supported by the C compiler 
program!
:i1.Compiler
:li.:hp2.Assembler::ehp2. now that the assembler source has been 
produced by the compiler, this program will assemble it and store the 
output in an :hp2.object file.:ehp2. 
:i1.Assembler
:li.:hp2.Linker::ehp2. if the project comprises multiple C files,
:fn.Your STM32 C program projects will :hp1.always:ehp1. have multiple 
files!
:efn.
the linker will combine all of the assembled object files into one 
executable; it will also substitute in the memory addresses for 
function calls, variable usages, and other such things. It also adds 
:hp2.libraries:ehp2. into the program.
:i1.Linker
:eol.
:p.:hp5.To build a program,:ehp5. the STM32CubeIDE uses the 
:hp2.GCC:ehp2. C compiler and contains a C runtime library -- this 
library contains a variety of useful C library functions that you may 
have used in the past if you are already familiar with C.
:p.:hp5.After building a program:ehp5. (and if you click Run), the 
STM32CubeIDE will invoke a program that flashes the firmware image file 
that the linker produced onto the board!
:h3.About the Runtime Library
:p.In the world of C programs that run under the control of an 
:hp1.operating system,:ehp1. the C runtime library
:fn.For the curious, this library is named :pv.libc.a:epv. 
(:pv.libSystem.dylib:epv. on MacOS) on UNIX, and is split into three 
libraries on Windows: :pv.user32.lib:epv., :pv.kernel32.lib:epv., and 
:pv.gdi32.lib:epv..
:efn.
provides all manner of useful functions. You may recognize some of 
these:
:dl tsize=15.
:dt.:pk.malloc():epk. 
:dd.Allocate memory dynamically to a pointer
:dt.:pk.fopen():epk. 
:dd.Open a disk file
:dt.:pk.fread():epk. 
:dd.Read data from a disk file
:dt.:pk.fwrite():epk. 
:dd.Write data to a disk file
:dt.:pk.fclose():epk. 
:dd.Close a disk file
:dt.:pk.system():epk. 
:dd.Run a system command (any shell/terminal command)
:dt.:pk.exit():epk. 
:dd.Leave the program and return to the shell or file browser
:edl.
:p.Unfortunately, :hp5.you cannot use any of these in your STM32 
programs!:ehp5. Because the STM32 isn't running an operating system, 
none of the above functions will work.
:fn.Granted, there is a :pk.malloc():epk. function, but it works 
:hp1.completely differently:ehp1. on the STM32 than it does on an 
operating system!
:efn.
:p.We will explore these runtime library functions later, but they will 
not be amazingly useful. Since this book may also be useful for those 
building their Capstone projects, understanding the library functions 
used for manipulating :hp2.strings:ehp2. will certainly help if you 
wish to have any textual output from your microcontroller (perhaps over 
a serial port or an external character display).
:h2.Debugging Process
:p.When you click on that :rk.Run:erk. or :rk.Debug:erk. button, 
STM32CubeIDE will invoke the above build process, but will then execute 
other tasks based on which of the two buttons you clicked:
:ul.
:li.:rk.Run:erk.
:ol.
:li.Microcontroller is reset
:li.Microcontroller is erased
:li.Program is flashed onto the microcontroller
:fn.By way of the ST-Link chip, found on the underside of the 
STM32L432KCU series boards and found at the top of the STM32F4xxx 
series boards
:efn.
:li.Microcontroller is reset
:eol.
:li.:rk.Debug:erk.
:ol.
:li.Microcontroller is reset
:li.Microcontroller is erased
:li.Program is flashed onto the microcontroller
:li.Microcontroller is reset into trace mode
:li.ST-Link debugger chip starts communicating with :pv.gdb:epv. on 
your computer
:li.The microcontroller runs the reset handler program, and that 
program program stalls your program at the first instruction of 
the:pk.main:epk. function until you click the  :rk.Continue:erk. button
:eol.
:eul.
:h2.Object Files and Library Files
:p.The assembler will create object files, which are special files that 
contain a header followed by one or more groups of :hp1.machine 
code:ehp1. and :hp1.data.:ehp1. Any references to variables and 
functions, however, will be left as :q.blanks:eq. to be filled in by 
the linker later (since the linker will know about the memory address 
requirements of either the target microprocessor or operating system).
:i1.Object File
:p.Likewise, one can also create a :hp2.library:ehp2. that contains 
several object files in some kind of collection -- you can then pass 
one of these to the linker and it will automatically fetch variable 
references and functions out of the library collection just as if you 
passed many object files to it.
:i1.Library File
:p.The C runtime library (which provides functions like 
:pk.strcpy:epk., :pk.memset:epk., and such) is also a, as the name 
implies, a library file linked with every program!
:h0.C Language Primer
:p.This section will provide a basic primer on the C language, syntax, 
and provide some basic code examples that do not require any 
STM32-specific features -- those features will be explored in the next 
section following this one!
:h1.Basic C Syntax
:p.Before learning more advanced topics, let us first understand the 
basic C program structure!
:h2.Comments
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.A :hp2.comment:ehp2. is a portion of the code that is not compiled; 
it provides you a way to put some textual blurbs in your program
:i1.Comments
:p.You should :hp1.always:ehp1. comment your code! In C, there are two 
ways to define comments, as shown here:
:fig width=column place=inline frame=rules.
:xmp.
// This is a simple single-line comment.
 
/* This is a different way to do a single-line comment. */
/* This can also be a
   multi-line comment! */
:exmp.
:figcap.Example comments
:efig.
:lblbox.Why are there two comment types?
:p.In the :q.olden days:eq. of C (like the original K&R C or C89, often 
called :hp1.ANSI C:ehp1.), you could only use the multiline comment 
form!
:p.When C++ came about in the late 1980s, the language designers came 
up with the :pv.//:epv. single-line comment form to alleviate the need 
to type an ending :pv.*/:epv. on every comment.
:p.As one might gather from this, there are :hp2.different versions of 
C!:ehp2.
:ul.
:li.K&R C, from the 1970s
:li.C89, from 1989 (ANSI C, the most commonly-implemented C in embedded 
compilers)
:li.C99, from 1999
:li.C11, from 2011
:li.C23, from 2023 (our STM32CubeIDE C compiler does not support any of 
these features, and they aren't useful to us)
:eul.
:elblbox.
:h2 id=vars.Defining Variables
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.The simplest thing we can do in a C program is to define some 
:hp2.variables;:ehp2. once we learn how to do this, we will define some 
:hp2.functions:ehp2. (which are just blocks of code that optionally 
return a variable -- if this seems confusing now, it will become clear 
soon).
:p.In C, variables are known by their name and their associated 
:hp1.type.:ehp1. :hp5.The type defines how much memory a variable will 
use, and how some operations behave!:ehp5. 
:fn.For instance, a comparison operation (like :pk.a < b:epk.) behaves 
differently on signed and unsigned types; these will be covered next!
:efn.
C has the following types:
:ih1.Data types
:ul.
:li.:hp2.integral types:ehp2. which are useful for storing numbers:
:i2.Integral types (char, short, int, long)
:ul.
:li.:pk.char:epk. -- 8-bit
:li.:pk.short:epk. -- 16-bit
:li.:pk.int:epk. -- 32-bit
:li.:pk.long:epk. -- also 32-bit
:fn.The reason that :pk.long:epk.s are 32 bits on the STM32 is because 
the STM32 is a 32-bit ARM CPU (something you probably remember from 
Computer Systems class)
:efn.
 
:eul.
:li.:hp2.Floating-point types:ehp2. for decimal values:
:i2.Floating-point types (float, double)
:ul.
:li.:pk.float:epk. -- basic IEEE-754 floating-point type (32 bits)
:li.:pk.double:epk. -- double-precision floating-point (64 bits)
:eul.
:li.:hp2.Pointer types:ehp2. used to reference objects in memory (this 
will be discussed in great detail later, as these are a difficult topic 
for new C programmers)
:i2.Other types
:li.:hp2.Array types:ehp2. which hold a collection of various items all 
of the same type
:li.:hp2.Structure types:ehp2. which allow you to create singular types 
that hold several sub-variables
:li.The special :hp2.void type:ehp2. used primarily in a function when 
the function has no return type
:eul.
:p.You should also note that the :hp1.integral types:ehp1. can be 
:hp2.signed:ehp2. or :hp2.unsigned:ehp2., wherein you can choose 
whether or not the C compiler will support the usage of negative values 
on a variable or not.
:i1.Signed
:i1.Unsigned
:p.By default, variables are signed unless prefixed by the 
:pk.unsigned:epk. keyword. Here are some example variable definitions:
:fig width=column place=inline frame=rules.
:xmp.
int myNumber;            // no defined default value
int otherNumber = 12;    // defaults to 12
float result = 12.34;    // a floating-point value
unsigned short val;      // example of an unsigned value
:exmp.
 
:figcap.Single variable definitions
:efig.
:p.We will look at actually :hp1.using:ehp1. these variables in a 
future segment.
:h3 id=c99type.C99 Datatypes
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.In addition to the standard datatypes covered above,the STM32CubeIDE 
C compiler (GCC) supports the :hp3.C99:ehp3. version of C... and 
therefore lets us use specific variable datatypes that have a certain 
number of bits contained within them (and can optionally be signed).
:p.In order to use these, you will need to have the :pk.#include 
<stdint.h>:epk. statement at the top of your program; for more on these 
:hp1.preprocessor directives,:ehp1. see :hdref refid=preproc..
:ih1.C99 datatypes
:i2.uint*
:i2.int*
:table cols='1i 1i 1i'.
:tcap.C99 Datatypes
:thd.
:c.:hp2.Type:ehp2.
:c.:hp2.Bits:ehp2.
:c.:hp2.Signed:ehp2.
:ethd.
:row split=yes.
:c.:pk.uint8_t:epk.
:c.8
:c.yes
:row split=yes.
:c.:pk.int8_t:epk.
:c.8
:c.no
:row split=yes.
:c.:pk.uint16_t:epk.
:c.16
:c.yes
:row split=yes.
:c.:pk.int16_t:epk.
:c.16
:c.no
:row split=yes.
:c.:pk.uint32_t:epk.
:c.32
:c.yes
:row split=yes.
:c.:pk.int32_t:epk.
:c.32
:c.no
:row split=yes.
:c.:pk.uint64_t:epk.
:c.64
:c.yes
:row split=yes.
:c.:pk.int64_t:epk.
:c.64
:c.no
:etable.
:h2 id=sizeof.Getting the Size of Variables
:p.C has a special keyword, :pk.sizeof:epk. that functions somewhat 
like a variable that the compiler will see and replace with the size of 
a variable's memory. You can use this whenever you need to find out how 
big a compound type is (like a :pv.struct:epv. or :pv.union:epv., which 
we will discuss later)!
:p.Usage is as follows:
:fig width=column place=inline frame=rules.
:xmp.
int myNumber;
int numSize = sizeof(myNumber);
int intSize = sizeof(int);
:exmp.
 
:figcap.sizeof example
:efig.
:p.The first :pv.sizeof:epv. computes the size of the named variable, 
and the second one computes the size of the generic :pk.int:epk. type.
:h2 id=arrays.Defining Arrays
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.Arrays in C are :hp5.fixed-size:ehp5. and may or may not have 
default values (just like shown above in the code example for single 
variable definitions).
:i1.Array
:p.Please note that arrays are closely related to a special C data type 
called a :hp2.pointer:ehp2.; see :hdref refid=ptrs. for more 
information. Please familiarize yourself with the basics in this 
section before getting overwhelmed by pointers, since they are a 
notorious stumbling block for novice C programmers!
:p.You declare arrays like this:
:fig width=column place=inline frame=rules.
:xmp.
int numbers&lbrk.32&rbrk.;                     // our array has 32 elements
unsigned char smallValues&lbrk.10&rbrk.;
:exmp.
 
:figcap.Arrays without initialization
:efig.
:h3.Array Initialization
:p.Of course, none of these arrays have any default value
:fn.As a matter of fact, these arrays not only have no default value, 
but will be filled with :hp1.random values:ehp1. that correspond to the 
uncleared reset state of the microcontroller's RAM!
:efn.
that is useful. As such, there are several ways of actually 
initializing an array:
:i2.Initialization
:ol.
:li.:hp2.Immediate Values:ehp2.
:p.This is the easiest way to initialize an array:
:xmp.
int myNumbers&lbrk.&rbrk. = &lbrc.
    5, 10, 15, 20, 25, 30
&rbrc.;
:exmp.
:note.Note that the array size is not present within the square 
brackets -- this array initialization scheme will automatically size 
the array to the number of elements that you type in.
:li.:hp2.String Initialization:ehp2.
:p.Use this format when you are defining a string (which uses the 
:pv.char:epv. type)
:xmp.
char myString&lbrk.&rbrk. = "Demo string";
:exmp.
:li.:hp2.Automatic Zero:ehp2.
:p.When defining an array that you will use later, it is a good idea to 
:hp1.zero the memory:ehp1. it will end up using:
:xmp.
int myNumbers&lbrk.10&rbrk. = &lbrc. 0 &rbrc.;
:exmp.
:li.:hp2.Designated Initializers:ehp2.
:p.Use this feature to assign array values at specific locations in the 
array:
:i3.Designated Initializer
:xmp.
int otherNumbers&lbrk.10&rbrk. = &lbrc.
    &lbrk.5&rbrk. = 5,
    &lbrk.7&rbrk. = 9
&rbrc.
:exmp.
:note.This is a C99 feature.
:eol.
:h2 id=structs.Defining Structures
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.If you've taken courses on Java in the past (which you will have 
done so if you are a computer engineer), you will be familiar with 
:hp1.classes:ehp1. and all that they entail; A :pv.struct:epv. in C is 
passingly similar to a class that contains only variables.
:i1.Structures (struct)
:p.For those that are confused, a :pv.struct:epv. will let you create a 
:hp5.compound type:ehp5. that itself is a custom data type that 
contains several other variables within it.
:p.Structs are defined as follows, and then instantiated as follows:
:fig width=column place=inline frame=rules.
:xmp.
struct MyStruct {              // declare the struct type
    int a;                     // members of the struct...
    char b;
    float c;
};
 
struct MyStruct myInstance;    // instantiate the struct
:exmp.
 
:figcap.Structure definition and instantialization
:efig.
:p.Now, some C programmers will choose to use the :pk.typedef:epk. 
keyword to avoid the need to type :pv.struct:epv. every time the 
structure type is referenced. You can use the :pv.typedef:epv. keyword 
like this:
:i2.typedef
:fig width=column place=inline frame=rules.
:xmp.
typedef struct {               // declare the struct type
    int a;                     // members of the struct...
    char b;
    float c;
} MyStruct;
 
MyStruct myInstance;           // instantiate the struct
:exmp.
 
:figcap.Structure typedef usage
:efig.
:p.You can write code like this that actually uses a :pv.struct:epv.:
:fig width=column place=inline frame=rules.
:xmp.
struct MyStruct {
    int a;
    char b;
    float c;
};
 
struct MyStruct myInstance;
 
// later on, in a function:
myInstance.a = 5;
myInstance.c = 12.34;
:exmp.
 
:figcap.Structure usage
:efig.
:h2 id=unions.Defining Unions
:p.When you are in a union, you are in a group with other people.
A:pk.union:epk. in C is of a similar idea, except it stores several 
variables overlapping in the same memory space! These have very 
specific uses and are :hp5.not:ehp5. :pv.struct:epv. types, and you 
will likely not need to use these unless you are reading in data sent 
by some external sensor.
:i1.union
:p.The syntax is like this:
:fig width=column place=inline frame=rules.
:xmp.
union Tester {                 // declare the union
    int a;                     // members of the union
    char b;
    float c;
} MyStruct;
 
union Tester myDemo;           // instantiate the union
myDemo.a = 5;                  // all 32 bits of the union are set
myDemo.b = 'x';                // only 8 bits are set
:exmp.
 
:figcap.Union definition syntax
:efig.
:p.The second assignment statement (:pv.myDemo.b = 'x';:epv.) will 
alter only the first 8 bits of the union,
:fn.Do note that :hp5.endianess:ehp5. matters here -- the STM32 ARM CPU 
is little-endian, so it will actually be bits 24 through 31 that store 
the :pk.char:epk.)!
:efn.
leaving the other 24 bits untouched and filled with whatever the first 
assignment set them to (which, if you used a negative number, would be 
mostly :pv.0xFF:epv. hex values).
:p.Unions are used just like structures, but remember that altering one 
of the :q.members:eq. of the union alters the value of every other 
member!
:h2 id=enums.Defining Enumerations
:p.An enumeration, or :pk.enum:epk. for short, allows you to assign 
user-written names to integer constants. These are particularly useful 
where you may have a variety of numbers that refer to the state of a 
program, but do not wish to recall a number corresponding to every 
state.
:i1.enum
:p.The syntax to define an :pv.enum:epv. is as follows:
:fig width=column place=inline frame=rules.
:xmp.
enum States {
    WAITING, READING, WRITING, CRASHING
};
 
enum States myProgramState;
 
// later on in a function:
myProgramState = WAITING;
:exmp.
 
:figcap.Enum definition and usage syntax
:efig.
:lblbox.Enum Name Limit
:p.Please note something :hp2.extremely important:ehp2. when using 
:pv.enums:epv.: you can only have one occurrence of every word in your 
program!
:p.In other words, you can't define two :pv.enums:epv. that both have a 
:pk.WAITING:epk. enumerator!
:elblbox.
:h2 id=ltrls.Extra Immediate Types
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.Throughout the examples we have seen so far, the variables have been 
defined as :hp1.plain signed integers:ehp1. or :hp1.character 
strings.:ehp1. In reality, there are many other ways of defining 
so-called :hp2.literals,:ehp2. the value that we assign a variable to 
equal:
:ih1.Immediate types
:ul.
:li.:hp2.Signed decimal&colon.:ehp2. 
:i2.Decimal
:xmp.int x = 5;
:exmp.
:li.:hp2.Unsigned decimal&colon.:ehp2. 
:fn.This employs a :hp2.cast:ehp2., which will be described in more 
detail later.
:efn.
:xmp.unsigned int y = (unsigned int) 1231431;
:exmp.
:li.:hp2.Hexadecimal&colon.:ehp2. 
:i2.Hexadecimal
:xmp.unsigned short demo = 0xAD52;
:exmp.
:li.:hp2.Binary&colon.:ehp2. 
:i2.Binary
:xmp.unsigned char keyValue = 0b11110000;
:exmp.
:li.:hp2.Octal&colon.:ehp2. 
:i2.Octal
:xmp.short testing = 0177;
:exmp.
:li.:hp2.Explicit :pk.long:epk.&colon.:ehp2. 
:i2.Long
:xmp.long myVar = 5423762L;
:exmp.
:li.:hp2.Single character:&colon.:ehp2. 
:i2.Character
:xmp.char val = 'a';
:exmp.
:li.:hp2.Character string&colon.:ehp2. 
:i2.String
:xmp.
char string&lbrk.&rbrk. = "This is a test";
:exmp.
:eul.
:h2 id=funcs.Defining Functions
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.In C, a :hp2.function:ehp2. is where your actual code goes -- to 
this point, we haven't actually written a line of code that results in 
the CPU having to do :hp1.anything!:ehp1. 
:i1.Function
:p.Let us start simple and create a :pk.void:epk. function that returns 
nothing, and simply performs addition within it:
:fig place=inline width=column frame=rules.
:xmp.
void myFunc() &lbrc.
    int a;       // declare a variable within the function
 
    a = 5;       // assign a value to the variable
    a = a + 2;   // add 2 to the variable
 
&rbrc.
:exmp.
 
:figcap.Basic function with no parameters or return
:efig.
:p.Something important to note is the critical concept of :hp2.variable 
scope:ehp2. -- this is the term that refers to the regions wherein, if 
you declare a variable, it can be used later. The general way to 
remember this is:
:i2.Scope
:lq.
:p.Variables declared within the body of a function will not be usable 
or accessible outside of the function, and variables declared outside 
of any function (such as at the top of the C source file) will be 
usable by :hp1.any:ehp1. function (and may be modified by any function 
too). :elq.
:p.Take the following function example that references variables that 
are :hp5.out-of-scope:ehp5.:
:fig width=column place=inline frame=rules.
:xmp.
void function1() {
    int x = 5;             // declare x
    x++;                   // increment x by 1
}
 
void function2() {
    x = 12;                // x is not in the scope
}
:exmp.
:figcap.Out-of-scope variable usage demonstration
:efig.
:p.The assignment of :pv.x:epv. in the second function will result in 
the displaying of a syntax error message by the compiler!
:h3 id=return.Return Types
:p.A function can also have a :hp2.return type:ehp2. -- the above 
examples use the :pk.void:epk. return type, which means there is 
:hp1.no:ehp1. return type. It is best to examine the syntax to define a 
function with a return type through example:
:i2.Return type
:fig width=column place=inline frame=rules.
:xmp.
int giveNumber() {
    return 5;
}
:exmp.
 
:figcap.Return-type function definition
:efig.
:lblbox.Returning Arrays
:p.Many novices wonder if they can return arrays. You can, but you 
cannot return :hp2.immediate arrays:ehp2., and you are really returning 
a :hp2.pointer.:ehp2. One may imagine a function like this:
:xmp.
char* giveString() {
    return "This is a sample";
}
:exmp.
:p.This will, however, :hp1.not:ehp1. work at all -- the value returned 
from the :pv.giveString():epv. function will actually be the memory 
address of the :pv."This is a sample":epv. string. This will result in 
the clobbering of the return address on the stack, resulting in a 
program hang.
:p.If this is confusing, don't worry! Just remember to not ever try to 
return an array!
:elblbox.
:h3.Function Parameters
:p.Functions can also have :hp2.parameters:ehp2. that allow you to pass 
immediates and variables into a function. If you pass a variable, its 
contents will be :hp1.copied:ehp1. into the function; as such, the 
value passed into the function should not be modified. To modify a 
value, you will need to use a pointer (which will be described later).
:i2.Parameters
:p.Here are a few function definitions that take parameters:
:fig width=column place=inline frame=rules.
:xmp.
int addTogether(int a, int b) {
    return a + b;
}
 
int addThree(int numbers&lbrk.&rbrk.) {
    return numbers&lbrk.0&rbrk. + numbers&lbrk.1&rbrk. + numbers&lbrk.2&rbrk.;
}
 
struct MyStruct {
    int intInStruct;
};
 
 
int extractStruct(struct MyStruct entry) {
    return entry.intInStruct;
}
:exmp.
 
:figcap.Functions with parameters (also array and structure)
:efig.
:h3 id=callfnc.Calling Functions
:p.The point of functions is to :hp2.call:ehp2. them, or invoke them.
Functions with no return type
:fn.That is, the :pk.void:epk. type.
:efn.
are called slightly differently than functions with a return type.
:p.Here is a sample of calling some functions :hp1.without:ehp1. return 
types:
:fig width=column place=inline frame=rules.
:xmp.
void callee() {
    // this function body would do something
}
 
void caller() {
    callee();                        // call the function
}
:exmp.
 
:figcap.Return-type function definition
:efig.
:p.Here is a sample of calling some functions with return types:
:fig width=column place=inline frame=rules.
:xmp.
int addTogether(int a, int b) {
    return a + b;
}
 
int addThree(int numbers&lbrk.&rbrk.) {
    return numbers&lbrk.0&rbrk. + numbers&lbrk.1&rbrk. + numbers&lbrk.2&rbrk.;
}
 
void callThem() {
    int sum;                         // will hold the sum
 
    sum = addTogether(2, 4);         // immediate parameters
 
    int num1 = 8;
    int num2 = 16;
    sum = addTogether(num1, num2);   // variable parameters
 
    int numbers&lbrk.&rbrk. = {5, 10, 15};     // our array
    sum = addThree(numbers);         // array parameter
}
:exmp.
 
:figcap.Calling functions with return types
:efig.
:h3.The Main Function
:p.Your program will :hp5.always:ehp5. start with a function named 
:pk.main:epk., with an :pv.int:epv. return type. This is defined as 
follows:
:fig width=column place=inline frame=rules.
:xmp.
void somecode() {
    // this function body would do something
}
 
int main() {                         // program starts here
    somecode();
}
:exmp.
 
:figcap.Main function definition
:efig.
:lblbox.The Startup Code
:p.Before the microcontroller CPU gets to the :pk.main:epk. function, 
it runs the :hp2.startup code:ehp2. -- this code finishes, then 
branches to the start of your code at the :pk.main:epk. function.
:elblbox.
:p.No matter how complicated your program may be, it will 
:hp5.always:ehp5. start in the main function -- this cannot be changed!
:h3 id=inline.Inline Functions
:p.For optimization reasons, the C99 version of the language permits 
you to create :hp2.inline functions:ehp2. that results in the assembler 
code for the function being deposited straight into the code that 
called the function. Here is an example inline function:
:i1.inline
:fig width=column place=inline frame=rules.
:p.Source code in file:
:xmp.
inline int add(int a, int b) {
    return a + b;
}
 
int main() {
    display(add(5, 2)); // show our number on a display screen
}
:exmp.
:p.Effective code:
:xmp.
int main() {
    display(5 + 2);
}
:exmp.
 
:figcap.Inline function definition
:efig.
:h1 id=control.Flow Control
:p.Inevitably, in the course of writing your program, you will want to 
add in :hp1.branches:ehp1. for decision-making. In C, you have a 
variety of :hp5.control flow statements:ehp5. you can write into your 
program:
:ul.
:li.:pk.if:epk. statements, for checking the status of one or more 
variable and running a block of code :hp1.once:ehp1.
:li.:pk.while:epk. statements, for repeatedly checking the status of 
one or more variables and running a block of code :hp1.once or more 
than once:ehp1.
:li.:pk.switch/case:epk. statements, for making a :q.lookup table:eq. 
and running a small amount of code :hp1.once:ehp1. 
:eul.
:h2 id=ifstmt.If Statements
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.The simplest of the control flow statements is the first one in the 
above list, the :pk.if:epk. statement. This statement is of the 
following syntax:
:i1.if
:fig width=column place=inline frame=rules.
:xmp.
if(100 > 10) {  // this is the "condition"
    // this code will always run
}
:exmp.
 
:figcap.Example if statement definition
:efig.
:p.This can, of course, be more complex; please see 
:hdref refid=elseif..
:h3.Conditions
:p.The :hp2.condition:ehp2. within the :pk.if:epk. statement body (or 
:pk.while:epk. statement, or :pk.for:epk. statement) contains a 
comparison operation, which are of the following forms:
:i2.Conditions
:dl tsize=15.
:dthd.Condition
:ddhd.Explanation
:dt.:pk.a == b:epk. 
:dd.Does :pv.a:epv. equal :pv.b:epv.?
:dt.:pk.a != b:epk. 
:dd.Does :pv.a:epv. not equal :pv.b:epv.?
:dt.:pk.a < b:epk. 
:dd.Is :pv.a:epv. less than :pv.b:epv.?
:dt.:pk.a > b:epk. 
:dd.Is :pv.a:epv. greater than :pv.b:epv.?
:dt.:pk.a <= b:epk. 
:dd.Is :pv.a:epv. less than or equal to :pv.b:epv.?
:dt.:pk.a >= b:epk. 
:dd.Is :pv.a:epv. greater than or equal to :pv.b:epv.?
:dt.:pk.a:epk. 
:dd.Is :pv.a:epv. greater than :pv.0:epv.? Remember that :pv.0:epv. is 
:hp1.false,:ehp1. and anything greater than :pv.0:epv. is 
:hp1.true!:ehp1. 
:edl.
:p.
:p.The condition may use one or two constants or variables.
:fn.If this is confusing: you can compare a variable against a 
constant, two variables against each other, or two constants against 
each other (this is very rarely done, though)
:efn.
:h3 id=boolean.Multiple Conditions/Logical Operators
:note.These are sometimes called :hp2.boolean operators!:ehp2. 
:i1.Boolean operators
:p.In addition to having a single condition statement, you can also 
have :hp1.several:ehp1. condition statements if you choose to use 
:hp2.logical operators:ehp2. like these:
:i1.Logical operators
:dl tsize=15.
:dthd.Condition
:ddhd.Explanation
:dt.:pk.a && b:epk. 
:dd.And
:dt.:pk.a || b:epk. 
:dd.Or
:dt.:pk.a ! b:epk. 
:dd.Not
:edl.
:p.:warning.:pk.a & b:epk. and :pk.a | b:epk. are :hp5.different:ehp5. 
from these statements, and are instead :hp1.bitwise operators:ehp1. 
that we discuss in :hdref refid=bitwise.!:ewarning.
:p.You would use them like this:
:fig width=column place=inline frame=rules.
:p.And:
:xmp.
if((a == b) && (c != d)) {
    // use parenthesis adequately to avoid confusion!
}
:exmp.
:p.Or:
:xmp.
if(a == b) || c) {
    // this is if a equals b and c is greater than zero
}
:exmp.
:p.Not:
:xmp.
if(!a && !(b < c)) {
    // the distributive property applies, like DeMorgan's Theorem
}
:exmp.
 
:figcap.If statements with logical operators
:efig.
:h3 id=elseif.Else-If Statements (and Else)
:p.Inevitably, you may want to have a decision that has more than one 
exit (up to this point, all of the statements we have looked at contain 
only one exit) -- you can create these by using the :pk.else if:epk. 
and :pk.else:epk. statements.
:i2.else If
:i2.else
:p.This looks like this:
:fig width=column place=inline frame=rules.
:xmp.
if(decision1) {
    // this code runs if "decision1" is true
}
else if(decision2) {
    // this code runs if "decision2" is true
}
else if(decision3) {
    // this code runs if "decision3" is true
}
else {
    // this runs if none of the above decisions are true
}
:exmp.
 
:figcap.Full If statement definition
:efig.
:p.The purpose of :pk.else if:epk. and :pk.else:epk. is to allow you to 
have a :hp1.multiple-way-out decision:ehp1. given a single :pk.if:epk. 
statement.
:h2 id=while.While Statements
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.If you want to create a :hp3.loop,:ehp3. you will want to use a 
:pk.while:epk. loop (or a :pk.for:epk. loop, described in 
:hdref refid=forloop.).
:i1.while
:p.A :pk.while:epk. loop will execute a block of code as long as a 
given :hp1.condition:ehp1. (just like in an :pk.if:epk. statement) 
remains true. By default, the code is ran :hp5.after:ehp5. the 
condition check, but we will examine a version of a :pk.while:epk. 
statement that runs the code :hp5.before:ehp5. the check.
:p.The syntax of a :pk.while:epk. statement is as follows:
:fig width=column place=inline frame=rules.
:xmp.
int a = 1;
 
while(a == 1) {
    if(key == 12345) {
        a = 0;
    }
    // run this forever until the "key" is set to 12345 elsewhere
}
:exmp.
:figcap.While statement definition
:efig.
:p.:warning.If you are checking if two variables are equal, you need to 
remember to do :pk.while/if(a == b):epk. and not :pk.while/if(a = 
b):epk., because the second statement will merely set :pv.a:epv. equal 
to :pv.b:epv. (and will always evaluate to :hp1.true:ehp1. no matter 
what the statement is, so the :pv.if/while:epv. statement will always 
run!:ewarning.
:p.In order to construct a :hp3.loop:ehp3., you can have an inequality 
check for the condition statement:
:fig width=column place=inline frame=rules.
:xmp.
int a = 0;
 
while(a < 10) {
    // code here will run 10 times
    a--;
}
:exmp.
:figcap.While statement loop
 
:efig.
:p.In this example, :pv.a++:epv. increments the variable :pv.a:epv. by 
one. :hp2.For more information,:ehp2. see :hdref refid=math.. :hp5.You 
will probably want to go read that section and then come back!:ehp5.
:p.A :pk.while:epk. statement runs forever as long as the statement is 
:q.true.:eq. 
:fn.In C, a statement is :q.true:eq. as long as it evaluates to a value 
that isn't zero. As such, :pv.while(1):epv. will result in an infinite 
loop!
:efn.
:h3.Premature Exiting
:p.If at any point you wish to either :hp1.exit from a loop:ehp1. or 
:hp1.jump to the next iteration:ehp1., you can use the following two 
keywords to do this:
:i1.break
:i1.continue
:ul.
:li.:pk.break:epk.
:li.:pk.continue:epk. 
:eul.
:p.Here is a complex :pv.while:epv. loop that uses both of these:
:fig width=column place=inline frame=rules.
:xmp.
int a = 0;
 
while(a < 10) {
    if(a == 5) {
        break;              // leave early on the 5th run
    }
    if(a == 6) {
        continue;
    }
    a++;                    // increment the loop counter
}
:exmp.
:figcap.While loop with break/continue
:efig.
:h2 id=dowhile.Do-While Loops
:p.If you wish to construct a loop that :hp1.runs code first:ehp1. then 
checks the condition, you can use a :pk.do-while:epk. loop. The syntax 
is relatively similar to a standard :pv.while:epv. loop:
:i1.do
:fig width=column place=inline frame=rules.
:xmp.
int a = 0;
 
do {
    something();
    a++;
} while(a < 10);
:exmp.
:figcap.Do-while loop example
:efig.
:h2 id=forloop.For Statements
:p.The purpose of a :pk.for:epk. statement is primarily to construct 
loops that will run for a specific number of cycles, or until a certain 
condition has been met; it provides a more feature-rich version of a 
:pk.while:epk. statement. The syntax is follows:
:i1.for
:fig width=column place=inline frame=rules.
:xmp.
void forDemo() {
    for(initial; condition; change) {
        // this is the body
    }
}
:exmp.
 
:figcap.For statement definition
:efig.
:p.The three parts of the :pk.for:epk. statement are as follows:
:ol.
:li.:pk.initial:epk. defines the reset term for the variable (or 
variables -- you can have several); this sets the variable that counts 
how many iterations the loop runs to the starting value. With C99, you 
can also :hp1.define:ehp1. the variable and its associated type here.
:p.Example: :pv.i = 0:epv.
:li.:pk.condition:epk. is the condition statement that specifies when 
the loop will stop running. This is the same as what you would find in 
a :pk.while:epk. statement.
:p.Example: :pv.i < 10:epv.
:li.:pk.change:epk. specifies a single line of code that will run to, 
usually, change
:fn.Usually, increasing or decreasing.
:efn.
the variable (though you can also call a function that changes the 
variable).
:p.Example: :pv.i++:epv. 
:eol.
:p.In this example, :pv.i++:epv. increments the variable :pv.i:epv. by 
one. :hp2.For more information,:ehp2. see :hdref refid=math.. :hp5.You 
will probably want to go read that section and then come back!:ehp5. 
:lblbox.Too Many Semicolons!
:p.Interestingly enough, you can actually :hp1.omit:ehp1. any of the 
terms within a :pk.for:epk. loop. This is actually one of the ways you 
can create an infinite loop! It looks like this:
:xmp.for(;;) {
    // body
}
:exmp.
:elblbox.
:p.Putting it all together, here are sample :pk.for:epk. statements:
:fig width=column place=inline frame=rules.
:xmp.
void forDemo() {
    int i;
    int sum;
 
    // basic for loop with a predefined variable
    for(i = 0; i < 10; i++) {
        sum = sum + i;
    }
 
    // for loop with a variable defined in-statement
    for(int j = 10; j > 0; j--) {
        sum = sum - j;
    }
    // for loop with a dropped incrementor
    for(int k = 0; k < 10;;) {
        sum = sum + k;
        k++;
    }
}
:exmp.
 
:figcap.For statement examples
:efig.
:h2 id=switch.Switch Statements
:p.Rather than having tons of back-to-back :pk.else if:epk. statements, 
you can use a :pk.switch:epk. statement to streamline the process!
:i1.switch
:i2.case
:p.A :pk.switch:epk. statement is contains a :q.body:eq. that has one 
or more :pk.case:epk. statements that actually perform actions 
depending on the value of a variable. The definition is as follows:
:fig width=column place=inline frame=rules.
:xmp.
void caseDemo() {
    switch(myVariable) {
    case 1:
        doFunction1();             // for myVariable == 1
        break;
    case 2:
        doFunction2();             // myVariable == 2
        break;
    case 3:                        // etc...
    case 4:
        doFunction3and4();
        break;
    default:
        doFunctionOthers();
    }
}
:exmp.
 
:figcap.Switch/case statement definition
:efig.
:p.The purpose of the :pk.break:epk. statement is to provide an 
:hp2.exit:ehp2. from the :pk.case:epk. block it is found in. If you 
forget to code in the :pk.break:epk. statements for your 
:pk.case:epk.s, you will end up accidentally running every code block 
for every case!
You can, of course, do some interesting things with this -- see the 
call to :pv.doFunction3and4():epv. for an example of two back-to-back 
cases that result in the same code chunk being executed.
:h1 id=math.Math Operations
:h2.Arithmetic Operations
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.Though you saw variable addition in :hdref refid=callfnc., you may 
also wish to know the other arithmetic operations that you can perform.
Here is a list of them:
:i1.Arithmetic
:dl tsize=15.
:dt.:pk.a + b:epk. 
:dd.Addition
:dt.:pk.a - b:epk. 
:dd.Subtraction
:dt.:pk.a * b:epk. 
:dd.Multiplication
:dt.:pk.a / b:epk. 
:dd.Division (quotient)
:fn.Note! This is :hp2.integer division:ehp2. if the first value is an 
integer! For :hp2.decimal division:ehp2., the numerator must be a 
floating-point variable or immediate!
:efn.
:dt.:pk.a % b:epk. 
:dd.Modulus (remainder)
:dt.:pk.a++:epk. 
:dd.Increment by 1
:dt.:pk.a--:epk. 
:dd.Decrement by 1
:edl.
:h3.Pre or Post Increment?
:p.Often times, the increment/decrement operators are used to great 
effect in :pv.while:epv.-loop containing blocks like this:
:i2.Increment/Decrement Pre/Post
:fig width=column place=inline frame=rules.
:xmp.
int a = 0;
int coolArray&lbrk.10&rbrk. = { ... };
 
while(a < 10) {
    doSomething(coolArray&lbrk.a++&rbrk.);
}
:exmp.
:figcap.Post-increment loop example
:efig.
:p.In this example, variable :pv.a:epv. will be incremented 
:hp2.after:ehp2. it is read and used for the array index for 
:pv.coolArray:epv. there in the loop body. This ensures that the loop 
will properly exit without running out-of-bounds.
:p.However, you can change the position of that :pk.++:epk. operator to 
make it such that reading the variable returns the :hp5.current:ehp5. 
value:
:fig width=column place=inline frame=rules.
:xmp.
int result = 0;
int numbers&lbrk.&rbrk. = {1, 2, 3, 4, 5};
 
void demo() {
    int i = 0;
    for(i = 0; i < 5; i++) {
        result += ++numbers&lbrk.i&rbrk.;   // add 1 to numbers&lbrk.i&rbrk. before
    }
}
:exmp.
:figcap.Pre-increment loop example
:efig.
:h2 id=bitwise.Bitwise Operations
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.If you wish to preform :hp2.binary operations,:ehp2. you can use 
bitwise operations! These let you manipulate individual bits within a 
variable, and will be :hp1.amazingly:ehp1. useful later when we begin 
manipulating STM32 peripherals!
:p.Here are the bitwise operators:
:dl tsize=15.
:dthd.Operator
:ddhd.Explanation
:dt.:pk.a & b:epk. 
:dd.:pv.a:epv. AND :pv.b:epv.
:dt.:pk.a | b:epk. 
:dd.:pv.a:epv. OR :pv.b:epv.
:dt.:pk.a &caret. b:epk. 
:dd.:pv.a:epv. XOR :pv.b:epv.
:dt.:pk.a << b:epk. 
:dd.Shift :pv.a:epv. left :pv.b:epv. times
:dt.:pk.a >> b:epk. 
:dd.Shift :pv.a:epv. right :pv.b:epv. times
:dt.:pk.a ~ b:epk. 
:dd.:pv.a:epv. NOT :pv.b:epv. 
:edl.
:note.These are different than the boolean/logical operators talked 
about at :hdref refid=boolean.!
:p.To actually use these bitwise operators, please examine the 
following sample. The :hp1.binary literal:ehp1. format is described in 
:hdref refid=ltrls..
:fig width=column place=inline frame=rules.
:xmp.
char a = 0b0001 & 0b0100; // a = 0101
char b = 0b0111 | 0b1000; // b = 1111
char c = ~0b1010;         // c = 0101
:exmp.
:figcap.Bitwise operations and binary literals
:efig.
:h2.Shorter Operations
:p.Sometimes, you may have a statement like this:
:xmp.sum = sum + 2;
:exmp.
:p.This is actually the :hp2.long:ehp2. way to write this! It can be 
abbreviated as follows:
:xmp.sum += 2;
:exmp.
:p.The following other operators exist:
:dl tsize=15.
:dthd.Operator
:ddhd.Explanation
:dt.:pk.a += b:epk. 
:dd.Addition
:dt.:pk.a -= b:epk. 
:dd.Subtraction
:dt.:pk.a *= b:epk. 
:dd.Multiplication
:dt.:pk.a /= b:epk. 
:dd.Division
:dt.:pk.a %= b:epk. 
:dd.Modulus
:dt.:pk.a |= b:epk. 
:dd.OR
:dt.:pk.a &caret.= b:epk. 
:dd.XOR
:dt.:pk.a &tilde.= b:epk. 
:dd.NOT
:edl.
:h1 id=ptrs.Pointers
:p.The most difficult thing in C to grasp, by far, is the concept of a 
:hp2.pointer.:ehp2. While there are many difficult and convoluted ways 
of describing a pointer, I have narrowed it down to three that should 
:q.click:eq. in your brain and provide a decent synopsis of what these 
mythical types are:
:i1.Pointer
:ol.
:li.A pointer is a special type of variable that stores a memory 
address to another variable as its contents -- in other words, 
:hp1.where a value is in memory.:ehp1.
:li.A pointer can be used to access any location in memory when 
assigned to a value that itself is a numeric immediate containing a 
memory address.
:li.:hp2.Dereferencing:ehp2. a pointer lets you work with the contents 
of memory located at the memory address stored in the pointer, may it 
be reading or writing.
:eol.
:p.Since we are targeting an STM32 and will therefore need to 
:hp1.directly:ehp1. access memory to control various things like I/O 
configuration registers and whatnot, mastering pointers will be 
:hp5.very:ehp5. important!
:note.All of the I/O operations on our STM32 involve the usage of 
pointers, but these are defined in a header file for you.
:h2.Defining and Using Pointers
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.Pointers can be defined simply by inserting a :pk.*:epk. between a 
variable's type definition and its name. There are actually 
:hp1.three:ehp1. different ways to define a pointer, all of which are 
valid:
:fig width=column place=inline frame=rules.
:xmp.
int* x;
int *y;
int * z;
:exmp.
:figcap.Basic pointer definitions
:efig.
:lblbox.The Great Pointer Debate
:p.Did you know that there is :hp1.no:ehp1. consensus on which of the 
three pointer definition styles is correct? Some argue that the first 
is correct, because the second looks like the :hp1.dereference:ehp1. 
operator (we will look at that next) and the third looks like 
multiplication! Others argue that the second is correct because you 
can't define multiple pointers on the same line if you use the first or 
third style! The truth is that :hp1.all:ehp1. of them are correct, and 
you can use whichever one you want!
:p.I, personally, use the first style on account of the explanation 
given about it looking rather similar to the dereferencing operator.
:elblbox.
:h3.Using Pointers
:p.Now that you have seen how to define pointers, let us see how they 
are used. The simplest thing you can do with a pointer is fill it with 
the memory location of an already-defined variable. Once our pointer is 
defined, we will then manipulate the variable it points to 
:hp1.through:ehp1. the pointer. This looks like this:
:i2.Address-of operator
:fig width=column place=inline frame=rules.
:xmp.
int x = 50;
int* y = &x;        // & means "the address of"
 
// note the following function takes an int, not an int pointer!
void print(int number) {
    // magically show the "number" on the screen somehow...
}
 
void pointerDemo() {
    x = 51;         // change x to 51, y remains the same
    print(*y);      // display what y points to, which is x = 51
    *y = 52;        // y points to x and just changed x to 52
    print(*y);      // display what y points to, which is x = 52
    print(x);       // this also displays 52
    print(&x)       // print the memory address of x, 0x20000000
    print(&y)       // print the memory address of y, 0x20000004
}
:exmp.
:figcap.Pointer usage example
:efig.
:p.Whenever you see :pk.*y:epk., this is called 
:hp5.dereferencing.:ehp5. 
:i2.Dereferencing
:p.As you can see, both :pv.x:epv. and :pv.y:epv. are themselves 
:hp5.variables:ehp5.; pointers are definitely a type of their own
:fn.As in, pointers are a distinct type in the same way that integral 
types, floating-point types, and function types are distinct types.
:efn.
, but that does not mean they don't have a memory address!
:lblbox.Why are the memory addresses what they are?
:p.On our STM32, the ROM starts at address :pv.0x08000000:epv. (this is 
where our program is) and the RAM starts at :pv.0x20000000:epv. Since 
we defined two variables, of the type :pk.int:epk., both consume 32 
bits of memory (or, 4 bytes). Therefore, :pv.x:epv. is at 
:pv.0x20000000:epv. and :pv.y:epv. is at :pv.0x20000004:epv.; if we had 
another variable, it would be at :pv.0x20000008:epv. (because the STM32 
uses 32-bit memory addresses, and each one results in 4 bytes of RAM 
being used).
:elblbox.
:p.Likewise, as you can see in the above sample, pointers are treated 
as variables when prepended by the :pk.*:epk. symbol; if you leave it 
off, setting or changing the  pointer will result in a change of the 
memory address that it points to (rather than the memory contents that 
the pointer itself points to).
:h3.Strings and Arrays as Pointers
:p.Strings are a special hybridization of arrays and pointers that are 
used to store blocks of text. When you define a string, like this:
:i2.Strings
:fig width=column place=inline frame=rules.
:xmp.char* myMessage = "this is a string";
 
:exmp.
:figcap.String definition example
:efig.
:p....you are actually defining :pv.myMessage:epv. as a pointer whose 
memory address numeric value is equal to the memory location where that 
message will eventually be stored. Likewise, you can define strings and 
arrays both like this (using the pointer syntax :hp1.or:ehp1. the array 
syntax):
:fig width=column place=inline frame=rules.
:xmp.
char myMessage&lbrk.&rbrk. = "this is array-style";
char* myOtherMessage = "this is pointer-style";
:exmp.
:figcap.Array-style string definition example
:efig.
:p.Likewise, we can define an array and then create a pointer to the 
first element of the array:
:fig width=column place=inline frame=rules.
:xmp.
int myNumbers&lbrk.&rbrk. = { 1, 2, 3, 4, 5 };
int* numbersPointer = &myNumbers;         // points to myNumbers
 
void pointerDemo() {
    print(myNumbers&lbrk.0&rbrk.);            // 1
    print(*numbersPointer);         // also 1
}
:exmp.
:figcap.Array/pointer intermixing
:efig.
:p.This may not seem useful now, but this will become :hp1.very:ehp1. 
useful later on when we get to pointer arithmetic; see 
:hdref refid=ptrmth. for more about this.
:h3.Structure Pointers
:p.
:artwork runin name=keyicon width=p18. This is a :hp3.key
concept!:ehp3.
:p.You can also define pointers to structures, but this changes how you 
use the structure. Just like you use the dereference operator to access 
a plain pointer to a plain variable, you must also dereference the 
structure pointer. However, there are actually :hp1.two:ehp1. operators 
for accessing the fields of a structure pointer! See the following 
example:
:i2.Structure pointer
:fig width=column place=inline frame=rules.
:xmp.
struct DemoStruct {
    int a;
    int b;
};
 
struct DemoStruct myStruct;
 
void structPointerDemo() {
    myStruct.a = 5;
    myStruct.b = 10;
 
    struct DemoStruct* myStructPointer;
 
    print(myStruct.a);                    // 5
    print(*(myStructPointer).a);          // also 5
 
    (*myStructPointer).a = 20;
    (*myStructPointer).b = 40;
    print(myStruct.a);                    // 20
    print(*(myStructPointer).a);          // also 20
 
    myStructPointer->a = 100;             // other deref style
    print(myStruct.a);                    // 100
    print(myStructPointer->a);            // also 100
}
:exmp.
:figcap.Structure pointer example
:efig.
:h2 id=ptrmth.Pointer Arithmetic
:p.One of the more confusing things about pointers is that you can 
perform arithmetic operations on them! This may not seem very useful to 
us since we are not really handling strings on our STM32 (and you 
normally see pointer arithmetic used in code that handles strings), but 
it is still a useful tool to have in your belt nonetheless.
:i2.Pointer arithmetic
:p.Something :hp3.critical:ehp3. to remember when using pointer 
arithmetic is to make sure that you always stay :hp2.aligned!:ehp2. If 
you have an array of :pk.int:epk.s, and you march through the array one 
byte at a time, you will not properly read the array since you'll be 
reading 3/4ths of an :pk.int:epk.!
:p.The following graphic shows two :pk.int:epk.s stored, back to back 
on a little-endian
:fn.The STM32 is :hp3.little-endian,:ehp3. meaning that multi-byte 
types (like :pk.int:epk.) are stored such that the lowest fourth of the 
four-byte :pk.int:epk. comes first.
:efn.
system:
:fig width=column place=inline frame=rules.
:xmp.int a = 12;
int b = 34;
:exmp.
:cgraphic.
&Ul.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv. 0C &Lv. 00 &Lv. 00 &Lv. 00 &Lv. 22 &Lv. 00 &Lv. 00 &Lv. 00 &Lv. content (little-endian)
&Tr.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Tl.
&Lv.         a         &Lv.         b         &Lv. variable
&Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
:ecgraphic.
:figcap.Storage of integers
:efig.
:p.Fortunately, any time you add or subtract to a pointer (either by 
using the increment/decrement operation or by adding or subtracting an 
integer to a pointer), the C compiler will automatically figure out the 
alignment for you.
:p.Going back to the above graphic, if you created a pointer to 
:pv.a:epv. then incremented it by one (:pv.a++:epv.), you should be 
moved over :hp5.four:ehp5. bytes such that the address increases by an 
entire :pk.int:epk. at a time.
:note.If you :hp1.cast:ehp1. the pointer type for your pointer to 
:pv.a:epv. to something that :hp1.isn't:ehp1. an :pk.int:epk. (like a 
:pk.char:epk.), you will then be responsible for ensuring correct 
alignment (because incrementing the :pk.char:epk.-casted pointer to 
:pv.a:epv. by 1 will not fully shift the memory address over into the 
next :pk.int:epk.). For more information on this, see 
:hdref refid=casts..
:p.Here is an example of scanning through an array using both the 
standard array syntax and by using pointer arithmetic:
:fig width=column place=inline frame=rules.
:xmp.
int myNumbers&lbrk.&rbrk. = { 1, 2, 3, 4, 5 };
void scan() {
    for(int i = 0; i < 5; i++) {
        print(myNumbers&lbrk.i&rbrk.);
    }
    for(int i = 0; i < 5; i++) {
        print(*(myNumbers + i));          // array-as-a-pointer
    }
}
:exmp.
:figcap.Pointer arithmetic array-scan example
:efig.
:p.I'm sure you have several questions about the code, specifically 
:q.why is the stop address not five times four:eq. and :q.why does 
:pv.i:epv. not increase by 4 every iteration?:eq. The answer to this is 
that when you perform pointer arithmetic, as mentioned before, you 
:hp5.must:ehp5. always remain aligned; the C compiler does the 
alignment for you such that you move only one offset to an array 
element at a time! Each :pk.int:epk. takes 4 bytes of memory, so the 
compiler must account for the true size of the array and also step 
forwards one :pk.int:epk. at a time. You, on the other hand, only have 
to move one index at a time and the compiler figures out the rest!
:p.Note that this is really similar to something you did back in ELEC 
2220 when you had to :hp1.type-cast:ehp1. variables in the debugger in 
order to properly :q.see:eq. what they consisted of; using the wrong 
type resulted in the displayed value in the debugger being wrong or 
incomprehensible!
:h2.Pointers as Arguments
:p.Sometimes, you may wish to write a function that actually 
:hp1.modifies:ehp1. one or more of its arguments! With pointer 
arguments, you can actually do this relatively easily. Since you pass 
the memory address into the function, none of the function-calling 
mechanics actually touch the variable that you are passing the pointer 
to. Examine the following code block for an example of this:
:fig width=column place=inline frame=rules.
:xmp.
int myNumber = 5;
 
void increase(int* input) {
    *input += 2;                  // increase the variable by 2
}
 
void demo() {
    print(myNumber);              // 5
    increase(&myNumber);
    print(myNumber);              // 7
}
:exmp.
:figcap.Function with a pointer argument
:efig.
:p.Of course, the :pk.&:epk. operator passes a pointer to 
:pv.myNumber:epv. into the :pv.increase():epv. function body.
:h2 id=fnptr.Function Pointers
:p.The :q.final boss:eq. of pointers is the difficult craft of 
:hp2.function pointers.:ehp2. These are pointers that, as the name 
implies, point to functions and allow you to call them. These are 
frequently used in a data structure called a :hp1.vtable:ehp1., but we 
will not be discussing those.
:i2.Function pointer
:p.Here is a sample of defining and using a function pointer:
:fig width=column place=inline frame=rules.
:xmp.
int add(int a, int b) {
    return a + b;
}
 
void demo() {
    int (*ptr)(int, int);         // leave off the arg names
    ptr = add;                    // set ptr to the address of add()
    int result1 = add(5, 10);
    int result2 = ptr(5, 10);
    int result3 = (*ptr)(5, 10);  // all three of these work!
}
:exmp.
:figcap.Function pointer example
:efig.
:p.As you can see, there are three valid ways of calling a function 
pointer.
:note.If you set a function pointer to an invalid address like some 
random memory address or to a variable, your microcontroller will crash!
:h2 id=casts.Casting
:p.A powerful feature found in C and almost always seen around pointers 
is the concept of a :hp2.cast.:ehp2. A cast permits you to transform 
the width of a variable (as in, the number of bytes that a variable 
takes up in memory) or its signage (signed or unsigned).
:p.Say that you declare a pointer of type :pk.void:epk. that points to 
some output buffer. Depending on the data type that you write to that 
pointer's memory location, different things may happen; let us assume 
that a simple character display controller watches the memory address 
:pv.0x001015A0:epv. and blasts text onto a screen. Here is a sample 
that implements a system like this:
:i1.Casting
:fig width=column place=inline frame=rules.
:xmp.
void* display = 0x001015A0;
 
void printString(char* text, int length) {
    for(int i = 0; i < length; i++) {
        *(char*)display = text&lbrk.i&rbrk.;
    }
}
 
void printInt(int value) {
    *(int*)display = value;
}
 
void demo() {
    char* message = "This is a test";
    printString(message, 14);
    int number = 5;
    printInt(number);
}
:exmp.
:figcap.Pointer casting example
:efig.
:p.As you can see, we started with a :pk.void:epk. pointer and 
converted it into either a :pk.char:epk. or :pk.int:epk. pointer based 
on which data type we wished to output.
:p.Something also very important (as discussed in :hdref refid=ptrmth.) 
is the understanding that if you change the type of a pointer pointing 
into an array to something else that :hp1.isn't:ehp1. the same as the 
original array definition type, you will be performing misaligned 
memory access and may get confused!
:lblbox.A KISS Warning
:p.One concern I have in ELEC 3040/3050 is a student using pointers, 
when unnecessary, to do relatively simple things. Take the :q.KISS:eq. 
(Keep It Simple, Stupid) approach!
:elblbox.
:h1 id=preproc.Preprocessor
:note.This information is primarily included for your own reference; 
you will not be using any of these features heavily in this class but 
may be using them later on in your studies and work!
:p.As you learned back at the start of this book, the 
:hp3.preprocessor:ehp3. is one of the stages/programs that is called 
when you compile your C program. The preprocessor uses various control 
statements to implement:
:ul.
:li.Macros
:li.Conditional compilation
:li.Custom errors and warnings
:li.Insertion of files
:fn.Primarily :hp2.headers.:ehp2. 
:efn.
:eul.
:p.The preprocessor statements always start with a pound (:pk.#:epk.) 
starting in the first column of a line of code. Let us examine some of 
these:
:h2.File Inclusion
:p.The most-commonly used function of the C preprocessor is 
the:pk.#include:epk. operator, which is used as follows:
:i1.include (preprocessor)
:xmp.#include <stm32l4xx.h>
:exmp.
:p.This will result in the contents of a file (at a specific location) 
named :pv.stm32l4xx.h:epv. being inserted into your program at the line 
the statement is on.
:p.:hp2.For a list of C headers you can use in your program,:ehp2. see 
:hdref refid=hdrs.!
:p.There are actually :hp1.two:ehp1. ways of specifying file paths:
:ol.
:li.If the filename is enclosed in :pk.< >:epk., the :hp5.system 
inclusion search path:ehp5. will be searched
:li.If the filename is enclosed in :pk." ":epk., the current directory
:fn.:q.Directory:eq. is an old term for what we call a 
:hp5.folder:ehp5. today, and is more frequently used in programming 
contexts!
:efn.
is searched
:eol.
:h3.Inclusion Search Path
:p.UNIX C compilers (including UNIX-style C compilers, which the GCC 
from STM32CubeIDE and ARM Clang from &mu.Vision are both considered) 
have a compiler argument that lets you specify a custom inclusion 
search path. Though you won't need to alter this path on STM32CubeIDE 
projects (as the IDE will automatically find any files in the 
:pk.inc:epk. directories of your project and add those to the search 
path), a Project Setting entry will let you add more directories.
:h2.Macros
:p.A :hp3.macro:ehp3. is a very useful feature of the C preprocessor 
that allows you to avoid the need for typing in tons and tons of code 
over and over; :hp5.a macro is a form of text substitution.:ehp5. 
:i1.define (preprocessor)
:p.Macros come in two varieties:
:ol.
:li.Text macros
:li.Macros with arguments
:eol.
:p.Let us examine text macros first. Say you have the following code:
:fig width=column place=inline frame=rules.
:xmp.
#define ANSWER 15
 
void doSomething() {
    if(input == ANSWER) {
        ...
    }
    ...
}
:exmp.
:figcap.Text macros example
:efig.
:p.This example shows a macro definition that will replace any 
occurrences of the text :pv.ANSWER:epv. in the program with 
:pv.15:epv., irrespective of context.
:h3.Macros With Arguments
:p.Sometimes, you may want to use a macro to replace a block of code -- 
for instance, if your program has lots of back-to-back :pk.else if:epk. 
statements with similar condition checks, it may make sense to use a 
macro that takes an argument.
:p.Examine the following sample code:
:fig width=column place=inline frame=rules.
:xmp.
#define CHECK(number) if(answer == number)
 
int decision(int answer) {
    CHECK(1) {
        return 12;
    }
    CHECK(2) {
        return 24;
    }
    return 0;          // fall-through if no cases match and leave
 
}
:exmp.
:figcap.Macro with argument example
:efig.
:p.This may seem rather confusing, so, let's expand the macro and see 
what the generated code that the compiler will actually end up 
compiling looks like:
:fig width=column place=inline frame=rules.
:xmp.
int decision(int answer) {
    if(answer == 1) {
        return 12;
    }
    if(answer == 2) {
        return 24;
    }
    return 0;          // fall-through if no cases match and leave
 
}
:exmp.
:figcap.Macro with argument example (expanded)
:efig.
:h3.Semicolon Consumption
:p.The C compiler will consume (i.e. skip past) as many semicolons as 
it can until the next statement is seen. A semicolon on its own, not 
associated with any code, is called a :hp2.null statement.:ehp2. Such a 
thing would look like this:
:i1.Null statement
:fig width=column place=inline frame=rules.
:xmp.
int doSomething() {
    return 1;;;;;;;;;;;
}
:exmp.
:figcap.Null statement example
:efig.
:p.Believe it or not, this is :hp1.completely:ehp1. valid! This can 
become useful when we wish to have a statement that might look cleaner 
as a macro, like this for example:
:fig width=column place=inline frame=rules.
:p.Un-expanded:
:xmp.
#define LEAVE(n) return n;
 
int doSomething() {
    LEAVE(5);
}
:exmp.
:p.Expanded:
:xmp.
int doSomething() {
    return 5;;
}
:exmp.
:figcap.Null statement example with macro
:efig.
:p.Note that double semicolon there in the macro-expanded version of 
the code.
:h3.Multiline Macros
:p.If you ever need to make a macro have multiple lines, you will need 
to use the :hp2.backslash:ehp2. key (:pk.\:epk.). Here is an example of 
a multiline macro:
:fig width=column place=inline frame=rules.
:xmp.
#define CHECK_LEAVE(target, value) \
    if(entry == target) {          \
        return value;              \
    }                              // no backslash here!
 
int lookupTable(int entry) {
    CHECK_LEAVE(5, 12);            // null statement!
    CHECK_LEAVE(8, 41);
    CHECK_LEAVE(10, 63);
}
:exmp.
:figcap.Multiline macro example
:efig.
:p.You will want to use the backslash on all lines :hp1.except for the 
last line.:ehp1.
:h3.Command-line definition
:p.You can also define macros on the C compiler command line with 
the:pk.-D:epk. argument, like so:
:xmp.cc -c myfile.c -DMYMACRO=1
:exmp.
:p.This defines the macro :pv.MYMACRO:epv. and sets its value to 1. You 
would want to use this to implement conditional compilation; look down 
the page a bit to learn about that.
:note.Please don't use command-line macro definition to define anything 
more sophisticated than simple variable substitution macros!
:h3.Undefining Macros
:p.If for whatever reason you wish to :hp1.undefine:ehp1. a macro after 
it is defined, you can do this pretty easily:
:i1.undef (preprocessor)
:xmp.#undef MYMACRO
:exmp.
:h2.Conditional Compilation
:p.:hp2.Conditional compilation:ehp2. is a term that refers to having a 
program that compiles differently based on the presence of certain 
variables. In the case of C, we implement this by testing whether or 
not a macro is defined (or by testing the value of a macro).
:p.There are two groups of keywords that are used to implement 
conditional compilation:
:i1.ifdef (preprocessor)
:i1.ifndef (preprocessor)
:i1.else (preprocessor)
:i1.endif (preprocessor)
:i1.if (preprocessor)
:i1.elif (preprocessor)
:ol.
:li.Generation 1
:ul.
:li.:pk.#ifdef:epk.
:li.:pk.#ifndef:epk.
:li.:pk.#else:epk.
:li.:pk.#endif:epk. 
:eul.
:li.Generation 2
:ul.
:li.:pk.#if:epk.
:li.:pk.#elif:epk.
:li.:pk.#else:epk.
:li.:pk.#endif:epk. 
:eul.
:eol.
:p.As one might imagine by the :q.generations:eq. of keywords listed 
above, the Generation 2 keywords were not available in C compilers 
before 1989.
:fn.For those interested in the history of C, there were several C 
compilers popular from 1990-1995 that did not fully implement the C89 
version of the C preprocessor, resulting in programmers being unable to 
use the Generation 2 preprocessor conditional compilation keywords!
:efn.
:p.Let us examine the usage of both of these:
:fig width=column place=inline frame=rules.
:p.Generation 1
:xmp.
#define DEBUG 1                    // you would change this
 
#ifdef DEBUG                       // use this code if DEBUG is set
void debugger() {
    // do something special in the debug version
}
#else
void debugger() {}                 // do nothing otherwise
#endif
:exmp.
:p.Generation 2
:xmp.
#define DEBUG 2                    // you would change this
 
#if DEBUG == 1                     // compare the value instead
void debugger() {
    // debugging type 1
}
#elif DEBUG == 2
void debugger() {
    // debugging type 2
}
#else
void debugger() {}                 // no debugging code
#endif
:exmp.
:figcap.Conditional compilation examples
:efig.
:p.Note that this feature allows you to have segments of code you may 
wish to include or exclude during development!
:h2.Custom errors and warnings
:p.You can use the C preprocessor to write your own errors and warnings 
into your program, which is useful if you are using conditional 
compilation and the user has specified some kind of irreconcilable 
difference or unusable sequence of configuration parameters.
:p.There are two keywords that implement this feature:
:ol.
:li.:pk.#warning:epk.
:li.:pk.#error:epk. 
:eol.
:p.Take the following example, modified from one above:
:fig width=column place=inline frame=rules.
:xmp.
#define DEBUG 2
 
#if DEBUG == 1
void debugger() {
    // debugging type 1
}
#elif DEBUG == 2
#warning "debugging type 2 selected! performance will be slower!"
void debugger() {
    // debugging type 2
}
#else
#error "no debugging type specified! cannot compile!"
#endif
:exmp.
:figcap.Custom error/warning example
:efig.
:h1 id=ilasm.Inline Assembly
:p.C allows you to code assembler statements directly into your 
program, without having to also have assembly files (like you did in 
Computer Systems class) linked into your project.
:fn.If you do that, this means you have to figure out how to make an 
assembly function that is compatible with the C function calling 
convention!
:efn.
:p.There are two :q.flavors:eq. of inline assembly:
:h2.Basic Inline Assembly
:p.If you wish to include totally static inline assembler statements 
that don't reference any variables, you can do so like this:
:i1.asm function
:fig width=column place=inline frame=rules.
:xmp.
void enableInterrupts() {
    __asm__("cpsie i");
}
:exmp.
:figcap.Basic inline assembly example
:efig.
:p.The :pk.cpsie i:epk. instruction means :q.Change Processor State, 
Interrupt Enable (Interrupts On).:eq.
:p.If you encounter issues, you can add :pv.volatile:epv. keyword to 
the statement such that the statement now reads :pk.__asm__ 
volatile("XXXX"):epk. 
:i2.volatile
:lblbox.Underscores
:p.This is really important -- there are :hp3.two underscores:ehp3. in 
:pv.__asm__:epv. statements; look really carefully as it may be rather 
hard to see them!
:elblbox.
:h2.Extended Inline Assembly
:p.If you wish to reference any variables, the compiler will allow you 
to substitute those into the assembler statements as :pk.%0:epk., 
:pk.%1:epk., etc. In other words, if you plug in a variable name, you 
will reference it as :pk.%0:epk. in the statement.However, if you use 
the more complicated :hp5.custom-named variable approach:ehp5., you can 
use an actual variable name instead of a number!
:i2.Extended syntax (percents)
:p.Likewise, you will need to specify the following things:
:ol.
:li.All of your :hp2.input operands:ehp2.
:li.All of your :hp2.output operands:ehp2.
:li.Any registers that your assembler statement altered, in the 
:hp2.clobber list:ehp2. 
:eol.
:p.Now, there are two forms of extended inline assembler statements:
:ol.
:li.Positional variables (this is the aforementioned :pk.%0:epk. thing)
:li.Custom-named variables
:eol.
:p.No matter which you use, they both follow the same basic syntax:
:fig width=column place=inline frame=rules.
:xmp.
void magic() {
    __asm__ volatile(
        "statement"         // the assembly statement
        : outputs           // output variables
        : inputs            // input variables
        : clobbers          // list of what we altered/changed
    );
}
:exmp.
:figcap.Extended inline assembly syntax
:efig.
:h3.Positional Variables
:p.The key thing to remember using this syntax form is that the 
variables you reference will be dropped straight into the assembler 
statement with format-specifier-style substitutions!
:fn.A :q.format specifier:eq. is the format string that the 
:pv.printf:epv. and :pv.scanf:epv. family of C library statements use.
See :hdref refid=fstring. for more information! You probably won't need 
to use these though!!
:efn.
:p.Here is an example, then we will look at what happens and why:
:fig width=column place=inline frame=rules.
:xmp.
void storer(uint32_t* address, uint32_t value) {
    __asm__ volatile(
        "str %1, &lbrk.%0&rbrk."
        :                             // outputs (none)
        : "r" value, "r" address      // inputs
        : "memory"                    // we modified memory
    );
}
:exmp.
:figcap.Extended inline assembly positional variables
:efig.
:p.Now, this statement has no outputs (since we aren't reading anything 
into any registers or memory addresses) and two inputs (the 
:pv.address:epv. and the :pv.value:epv.).
:p.The :pk."memory":epk. means that we are :hp3.modifying memory:ehp3. 
-- this function just simply stores a 32-bit variable at some memory 
address. If you are :hp3.modifying the condition code:ehp3. (which 
would occur if you use any math instructions), you would specify 
:pk."cc":epk. instead.
:p.You can also see the :q.constraint lists:eq. holding those 
:pk."=r":epk. terms. This tells the compiler to pick a register (or 
several) for your statement to use. You can get the compiler to 
allocate the following things for you:
:ul.
:li.:pk."=r":epk. is for a :hp2.register:ehp2.
:li.:pk."=w":epk. is for a :hp2.floating-point register:ehp2.
:li.:pk."=I":epk. places in an :hp2.integer constant:ehp2.
:li.:pk."=m":epk. is for a :hp2.memory address:ehp2. 
:fn.This is really for the Intel x86 or the IBM System Z instruction 
sets, where there is a specific way that you pass memory addresses
:efn.
 
:eul.
:lblbox.Register Naming
:p.Now, you might ask :hp1.:q.uhh, where in the world are the register 
names?!:eq.:ehp1. Well, you cannot just take any register and use it 
:hp1.because the compiler may be using that for a variable 
already!:ehp1. This is why you have to let the compiler figure out 
which registers you can use
:elblbox.
:h3.Custom-named Variables
:p.This syntax is a bit more advanced than the previous :q.simpler:eq. 
form of doing extended inline assembly. This one is as follows:
:p.Since this seems inconceivably difficult at first glance, let us 
examine a working example:
:fig width=column place=inline frame=rules.
:xmp.
uint32_t adder(uint32_t in1, uint32_t in2) {
    uint32_t answer;
 
    __asm__ volatile(
        "add %&lbrk.out&rbrk., %&lbrk.a&rbrk.,  %&lbrk.b&rbrk."
        : &lbrk.out&rbrk. "=r" (answer)         // outputs
        : &lbrk.a&rbrk. "r" (in1),              // inputs
          &lbrk.b&rbrk. "r" (in2)
        : "cc"                        // modified the cond. code
    );
 
    return answer;
}
:exmp.
:figcap.Extended inline assembly custom-named variables
:efig.
:p.This statement is passingly similar to the basic syntax example, 
except this one has an output register (since we need to get our result 
from the statement somehow). As you can see in the square brackets, we 
substitute in the names we want.
:h1.Storage Classes and Qualifiers
:p.In your program, you may wish to override the so-called :hp2.storage 
class:ehp2. of a variable. The storage class defines how a variable 
will be stored and how it will be moved around a function. Likewise, 
you may wish to add a :hp2.qualifier:ehp2. if you want to lock a 
variable or prevent the C compiler from optimizing access to the 
variable.
:fn.One might ask why they could possibly want to un-optimize 
something, and the answer is simple: you will want to use the 
:pk.volatile:epk. keyword (which this chapter discusses shortly after 
where this footnote appears) whenever you are using variables within 
interrupt service routines.
:efn.
:h2 id=storcls.Storage Classes
:p.There are four storage classes you can stick before the type of your 
variable:
:i1.auto
:i1.register (storage class)
:i1.static
:i1.extern
:ol.
:li.:pk.auto:epk.
:p.This defines the variable such that it is automatically created and 
destroyed when you enter a function. For a global variable,
:fn.A global variable is a variable defined :hp1.outside:ehp1. a 
function.
:efn.
this keyword does nothing; for a local variable,
:fn.A local variable is a variable defined :hp1.inside:ehp1. a function.
:efn.
it is the normal way of defining a variable. :hp5.By default, this 
keyword is secretly present on every variable:ehp5. and you don't need 
to type it every time since it's the stock behavior for every variable.
:li.:pk.register:epk.
:p.This forces a variable to stay located within registers. This 
keyword may have been seen in performance-critical C code back in the 
1980s, but your STM32's ARM processor has lots of registers and the C 
compiler has to put every variable in a register anyways (because ARM 
is RISC).
:li.:pk.static:epk.
:p.If you define a variable as :pv.static:epv. within a function, its 
value will persist across several runs of a function; this is the 
opposite of the behavior that :pv.auto:epv. instills and is 
:hp5.not:ehp5. the default unless you ask for it.
:li.:pk.extern:epk.
:p.If you define a variable with :pv.extern:epv., you are telling the C 
compiler that the variable cannot be found within the current C source 
file and that it should let the linker resolve the variable's name into 
an address. You can create :pv.extern:epv. references to any global 
variable in your program.
:eol.
:h2 id=quals.Qualifiers
:p.You can put a qualifier before the storage class to restrict the 
behavior of variables to certain conditions:
:i1.const
:i1.volatile (qualifier)
:ol.
:li.:pk.const:epk.
:p.Make a variable constant/read-only.
:li.:pk.volatile:epk.
:p.Make any access to a variable non-optimized. This is recommended for 
any variables that you use in interrupt service routines or IRQ 
handlers. The most common :q.volatile:eq. addresses are peripheral 
registers that are changed by an external source, and not by your 
program!
:li.:pk.restrict:epk.
:p.This is used to mark a pointer as the sole way to access a variable, 
and the base variable name that the pointer points to will never be 
used to access it. This is useful when you are using pointers to access 
arrays, and it allows the compiler to employ useful optimization 
techniques (like vectorization).
:eol.
:h2.Keyword Position Summary
:p.The following diagram shows the layout of these newly-introduced 
keywords on a variable definition.
:fig width=column place=inline frame=rules.
:cgraphic.
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv. qualifier &Lv.  sclass  &Lv.   type   &Lv.   name   &Lv.
&Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
:ecgraphic.
:figcap.Storage class/qualifier positioning
:efig.
:h3.Some Examples
:p.Here are a few examples of these keywords:
:fig width=column place=inline frame=rules.
:xmp.
volatile int myCounter = 2;
register char someChar = 'x';
const char* myString = "Hello world";
restrict uint32_t* someRegister = 0xC000251;
extern void someFunctionSomewhere(int a, char b);
:exmp.
:figcap.Storage class and qualifier examples
:efig.
:h1.C Keywords Reference
:p.Here is a series of useful tables that lists out the keywords we 
have learned about so far:
:h2.Flow Control
:p.These are your core keywords that control program execution.
:table cols='1i * 2i'.
:tcap.C Keywords: Flow Control
:thd.
:c.:hp2.Keyword:ehp2.
:c.:hp2.Description:ehp2.
:c.:hp2.Location:ehp2.
:ethd.
:row split=yes.
:c.:pk.break:epk.
:c.Exit from a :pv.while:epv., :pv.for:epv., or :pv.case:epv.
block
:c.:hdref refid=switch.
:row split=yes.
:c.:pk.case:epk.
:c.Start a region of code to run when the conditions on the
statement are met (within a :pv.switch:epv. statement)
:c.:hdref refid=switch.
:row split=yes.
:c.:pk.continue:epk.
:c.Jump to the next iteration of a :pv.while:epv. or
:pv.for:epv. loop immediately
:c.:hdref refid=while.
:row split=yes.
:c.:pk.default:epk.
:c.If no other :pv.case:epv. statements
match, this one will be ran (within a :pv.switch:epv.
statement)
:c.:hdref refid=switch.
:row split=yes.
:c.:pk.do:epk.
:c.Run a block of a :pv.while:epv. loop :hp1.before:ehp1. the
condition statement
:c.:hdref refid=dowhile.
:row split=yes.
:c.:pk.else:epk.
:c.Used in an :pv.if:epv. statement with or without some
:pv.else if:epv. statements to define conditions within the
:pv.if:epv. statement
:c.:hdref refid=elseif.
:row split=yes.
:c.:pk.if:epk.
:c.Run code if a condition is met
:c.:hdref refid=ifstmt.
:row split=yes.
:c.:pk.return:epk.
:c.Return a variable value when leaving a function body (only
for functions that return a type; :pv.void:epv. functions are
exempt from this)
:c.:hdref refid=return.
:row split=yes.
:c.:pk.switch:epk.
:c.Provide a simple way of evaluating multiple back-to-back
conditions in lieu of an :pv.if:epv. statement
:c.:hdref refid=switch.
:row split=yes.
:c.:pk.while:epk.
:c.Execute a block of code as long as a variable condition is
met (when seen alongside the :pv.do:epv. statement, run the code
:hp1.before:ehp1. the check)
:c.:hdref refid=while.
:etable.
:h2.Type Keywords
:p.These keywords specify variable types; the :pk.stdint.h:epk. types 
are a superset of these. For those, see the table in 
:hdref refid=c99type..
:table cols='1i * 2i'.
:tcap.C Keywords: Type Keywords
:thd.
:c.:hp2.Keyword:ehp2.
:c.:hp2.Description:ehp2.
:c.:hp2.Location:ehp2.
:ethd.
:row split=yes.
:c.:pk.int:epk.
:c.32-bit integer
:c.:hdref refid=vars.
:row split=yes.
:c.:pk.char:epk.
:c.8-bit ASCII character
:c.:hdref refid=vars.
:row split=yes.
:c.:pk.short:epk.
:c.16-bit small integer
:c.:hdref refid=vars.
:row split=yes.
:c.:pk.long:epk.
:c.32-bit integer (:pv.long:epv.s are 32 bits wide on 32-bit CPUs)
:c.:hdref refid=vars.
:row split=yes.
:c.:pk.float:epk.
:c.Single-precision floating-point number
:c.:hdref refid=vars.
:row split=yes.
:c.:pk.double:epk.
:c.Double-precision floating-point number
:c.:hdref refid=vars.
:row split=yes.
:c.:pk.void:epk.
:c.Lack of a type (only for functions and some pointers)
:c.:hdref refid=funcs.
:row split=yes.
:c.:pk.signed:epk.
:c.Store the value with 2's complement
:c.:hdref refid=vars.
:row split=yes.
:c.:pk.unsigned:epk.
:c.Don't store the value with 2's complement
:c.:hdref refid=vars.
:etable.
:h2.Storage Classes
:p.Use these before a variable type to control how it gets stored.
:table cols='1i * 2i'.
:tcap.C Keywords: Storage Classes
:thd.
:c.:hp2.Keyword:ehp2.
:c.:hp2.Description:ehp2.
:c.:hp2.Location:ehp2.
:ethd.
:row split=yes.
:c.:pk.auto:epk.
:c.Variable is created and destroyed whenever you enter and leave the
function (this is the default and you need not type it)
:c.:hdref refid=storcls.
:row split=yes.
:c.:pk.static:epk.
:c.Make a variable's value persist across several runs of a function
:c.:hdref refid=storcls.
:row split=yes.
:c.:pk.register:epk.
:c.Confine a variable to always be in a CPU register (the compiler
does this anyways for you)
:c.:hdref refid=storcls.
:row split=yes.
:c.:pk.extern:epk.
:c.Tell the compiler that it can find a variable's location in
memory in another C file (to be resolved by the linker later)
:c.:hdref refid=storcls.
:etable.
:h2.Variable Qualifiers
:p.Put these before your storage class to control what you can do with 
the variable!
:table cols='1i * 2i'.
:tcap.C Keywords: Variable Qualifiers
:thd.
:c.:hp2.Keyword:ehp2.
:c.:hp2.Description:ehp2.
:c.:hp2.Location:ehp2.
:ethd.
:row split=yes.
:c.:pk.const:epk.
:c.Make a variable a constant
:c.:hdref refid=quals.
:row split=yes.
:c.:pk.volatile:epk.
:c.Disable optimization for a variable; inform the compiler that
the variable's value may change at any time
:c.:hdref refid=quals.
:row split=yes.
:c.:pk.restrict:epk.
:c.Mark a pointer as being the only read/write path to the variable
it points to (the variable itself on the other side of the pointer
will only be accessed through this pointer)
:c.:hdref refid=quals.
:etable.
:h2.User-Defined Types
:p.These keywords declare custom types!
:table cols='1i * 2i'.
:tcap.C Keywords: User-Defined Types
:thd.
:c.:hp2.Keyword:ehp2.
:c.:hp2.Description:ehp2.
:c.:hp2.Location:ehp2.
:ethd.
:row split=yes.
:c.:pk.struct:epk.
:c.Define a structure compound type
:c.:hdref refid=structs.
:row split=yes.
:c.:pk.union:epk.
:c.Define a union compound type
:c.:hdref refid=unions.
:row split=yes.
:c.:pk.enum:epk.
:c.Define a list of enumerations that map to integers
:c.:hdref refid=enums.
:row split=yes.
:c.:pk.typedef:epk.
:c.Assign the name of one type to some custom name
(:pk.stdint.h:epk. does this)
:c.:hdref refid=structs.
:etable.
:h2.Special Operators
:p.These are special operators that aren't functions but behave like 
functions!
:table cols='1i * 2i'.
:tcap.C Keywords: Special Operators
:thd.
:c.:hp2.Keyword:ehp2.
:c.:hp2.Description:ehp2.
:c.:hp2.Location:ehp2.
:ethd.
:row split=yes.
:c.:pk.sizeof:epk.
:c.Have the compiler compute the size of a variable and substitute
in an integer where this keyword is found
:c.:hdref refid=sizeof.
:row split=yes.
:c.:pk.asm:epk.
:c.Define an inline assembler statement
:c.:hdref refid=ilasm.
:row split=yes.
:c.:pk.__asm__:epk.
:c.Alternate version of :pk.asm:epk. (note that there are two
underscores before and after the word)
:c.:hdref refid=ilasm.
:etable.
:h0.Programming the STM32
:p.Now that you understand the C language and its syntax/rules, we will 
now apply our knowledge and write some programs specifically for our 
STM32 board!
:h1.Basic STM32 Program Structure
:p.Before examining some of the tasks we can perform, let us first 
explore how we should start our program!
:note.This chapter will :hp5.not:ehp5. cover actually 
:hp1.creating:ehp1. projects -- if you need help with that, please see 
:hdref refid=mxproj.!
:h2 id=hdrs.Including the Headers
:p.The STM32 Development Toolchain (of which STM32CubeIDE provides for 
us) provides a number of important :hp3.headers:ehp3. we can use:
:i1.STM32 Headers
:table cols='1i *'.
:tcap.Base C Library Headers
:thd.
:c.:hp2.Header Name:ehp2.
:c.:hp2.Description:ehp2.
:ethd.
:row split=yes.
:c.:pk.float.h:epk.
:c.Floating-point type definitions
:row split=yes.
:c.:pk.limits.h:epk.
:c.Definitions for the largest numbers/maximums for each type
:row split=yes.
:c.:pk.math.h:epk.
:c.Various algebra and trig functions
:row split=yes.
:c.:pk.stdint.h:epk.
:c.C99 datatypes (:pv.uint32_t:epv. and others)
:row split=yes.
:c.:pk.string.h:epk.
:c.C string functions
:row split=yes.
:etable.
:table cols='1i *'.
:tcap.STM32 C Library Headers
:thd.
:c.:hp2.Header Name:ehp2.
:c.:hp2.Description:ehp2.
:ethd.
:row split=yes.
:c.:pk.stm32l4xx.h:epk.
:c.STM32L4xx (ELEC 3040/3050 board) definitions
:row split=yes.
:c.:pk.stm32f4xx.h:epk.
:c.STM32F4xx (ELEC 2220 board) definitions
:row split=yes.
:c.:pk.core_cm4.h:epk.
:c.Basic ARM Cortex-M4 components (automatically included)
:etable.
:h2.The Main Function
:p.Now that you know which headers you need to include,
:fn.Hint for 3040/3050: you want :pk.stm32l4xx.h:epk. at a minimum, and 
you likely want :pk.stdint.h:epk. too!
:efn.
let us look at the basic contents of a program.
:i1.main() function
:p.Here is the :q.minimum viable example:eq. you can use:
:fig width=column place=inline frame=rules.
:xmp.
#include <stm32l4xx.h>
#include <stdint.h>
 
int main() {
    // program goes here
}
:exmp.
:figcap.STM32 C program template (STM32L4xx board)
:efig.
:note.If you are using the Computer Systems board (perhaps you are 
reading this for a Capstone project), use the :pk.stm32f4xx.h:epk. 
header instead of :pk.stm32l4xx.h:epk.!
:h2.Program Startup Process
:p.While you certainly see that :pv.int main():epv. function, there are 
actually several other things that occur :hp1.before:ehp1. you enter 
your :pv.main:epv. function! Here they are:
:ol.
:li.The :pk.startup.s:epk. assembly-language program
:fn.This :pk.startup.s:epk. file is :hp5.always:ehp5. included with 
your program when you compile it, and is also device-dependent; for 
instance, the NUCLEO-32 board uses :pk.startup_+stm32l432kcup.s:epk. 
:efn.
initializes core system peripherals.
:li.The :pv.int main():epv. function is called.
:li.If your program exits from the :pv.main:epv. function, there is an 
infinite loop in :pk.startup.s:epk. that the program will land in.
:eol.
:h2.Filling Out Your Program
:p.You will, naturally, want to include more than just a :pv.main:epv. 
function that'll exit instantly. Here is a slightly more complex 
example that shows function definition and more:
:fig width=column place=inline frame=rules.
:xmp.
#include <stm32l4xx.h>
#include <stdint.h>
 
void GPIOsetup() {
    ...
}
 
void interruptsetup() {
    ...
}
 
void counter() {
    ...
}
 
int main() {
    GPIOsetup();
    interruptsetup();
    while(1) {
        counter();
        __asm__("wfi");
    }
}
:exmp.
:figcap.More-complex STM32 C program
:efig.
:p.As you can see in the above example, I have an assembly-language 
statement in the program! This is wrapped in the 
:pk.__asm__("XXXX"):epk. compiler built-in function. For more 
information on this, flip back to :hdref refid=ilasm..
:h1.GPIO
:p.The first thing you will want to configure are the :hp2.general 
purpose input/output:ehp2. pins -- these let your STM32 easily talk to 
the outside world. The GPIO pins, as you learned in Computer Systems 
class, are grouped into 16-pin :hp5.ports:ehp5. wherein each pin can be 
configured independently (but you end up accessing the entire port 
register at the same time for each pin).
:i1.GPIOx registers
:h2 id=moder.Basic Pin Configuration
:p.The STM32 device header you included includes :pv.struct:epv. 
definitions for the various GPIO registers as well as helpful textual 
macros that alleviate the need to type in individual bits using binary 
literals. Some of the registers we will be using in this exercise are:
:i2.MODER
:ul.
:li.The :hp5.Register and Clock Control:ehp5. register, :pk.RCC:epk.
:ul.
:li.:pk.RCC->AHB2ENR:epk. 
:fn.This is the C statement you will type in to use this register; 
:pk.RCC:epk. is a structure pointer, so you use the arrow operator 
:pk.->:epk to access the members. 
:efn.
-- the AHB2 peripheral clock enable register
:eul.
:li.The :hp5.GPIO:ehp5. registers, :pk.GPIOx:epk.
:ul.
:li.:pk.GPIOx->MODER:epk. -- the mode register that configures pins as 
inputs, outputs, alternates, or analogs
:li.:pk.GPIOx->IDR:epk. -- the register that allows you to 
:hp5.read:ehp5. GPIO pins (inputs)
:li.:pk.GPIOx->ODR:epk. -- the register that allows you to 
:hp5.write:ehp5. GPIO pins (outputs)
:eul.
:eul.
:p.There are several more, and you can find more information about 
these in the books listed in :hdref refid=biblio..
:p.Now, in order to actually configure GPIO pins, you must first 
:hp2.enable the GPIO clock.:ehp2. 
:fn.You have to do this because by default on the STM32, all of the 
peripherals are powered-down and must be manually enabled using one of 
the :pk.RCC:epk. control registers.
:efn.
To do this, simply set the :pv.GPIOAEN:epv. bit of:pk.RCC->AHB2ENR:epk.:
:fig width=column place=inline frame=rules.
:xmp.
#include <stm32l4xx.h>
 
void gpiosetup() {
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
    ...
}
 
int main() {
    gpiosetup();
    while(1) {
        __asm__("wfi");
    }
}
:exmp.
:figcap.GPIOA clock enablement
:efig.
:p.The :pv.stm32l4xx.h:epv. header has a macro that defines 
:pv.GPIOAEN:epv. as 1, which is the zeroth bit of the register (which 
corresponds to GPIOA's clock). Once the clock activates, we can 
configure the :hp2.mode register:ehp2. to set the behavior of each pin.
The :pk.GPIOA->MODER:epk. register is laid out as follows:
:fig width=column place=inline frame=rules.
:cgraphic.
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv. Px15  &Lv. PxNN  &Lv.  Px1  &Lv.  Px0  &Lv.
&Tr.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Tl.
&Lv. A &Lv. B &Lv. ..... &Lv. A &Lv. B &Lv. A &Lv. B &Lv.
&Ll.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lr.
:ecgraphic.
:figcap.GPIOx_MODER layout
:efig.
:p.The :pk.AB:epk. bit pattern for each register controls the mode, 
which can be one of the following:
:table cols='1i 2i'.
:tcap.GPIO MODER Bit Patterns
:thd.
:c.:hp2.AB:ehp2.
:c.:hp2.Mode:ehp2.
:ethd.
:row split=yes.
:c.:pk.00:epk.
:c.Input
:row split=yes.
:c.:pk.01:epk.
:c.Output
:row split=yes.
:c.:pk.10:epk.
:c.Alternate Function
:row split=yes.
:c.:pk.11:epk.
:c.Analog Mode
:etable.
:p.Given this information, say we want to enable :pk.PB3:epk. as output.
:fn.:pk.PB3:epk. corresponds to a green LED at the bottom-right of your 
Nucleo-L432 board!
:efn.
:note.You have to :hp5.clear the interesting bits beforehand:ehp5. 
using :pk.&=:epk., then set them to what you want with :pk.|=:epk. 
afterwards!
:p.The following code will configure PB3 as output:
:fig width=column place=inline frame=rules.
:xmp.
#include <stm32l4xx.h>
 
void gpiosetup() {
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN;   // note: GPIOB
    //   GPIOB pins:  3.2.1.0.
    GPIOB->MODER &= &tilde.0b11000000;           // clear bits
    GPIOB->MODER |=  0b01000000;           // set bits for output
}
 
int main() {
    gpiosetup();
    while(1) {
        __asm__("wfi");
    }
}
:exmp.
:figcap.PB3 output enablement example
:efig.
:lblbox.Clearing and Setting
:p.To clear bits, use this:
:xmp.GPIOA->MODER &= &tilde.0b11000000;
:exmp.
:p.To set bits, use this:
:xmp.GPIOA->MODER |= 0b11000000;
:exmp.
:note.You have to use the binary complement (i.e. NOT) operator to 
:hp1.invert:ehp1. to values for clearing, or you will do the reverse of 
what you wanted to!
:elblbox.
:h3.Outputting Values
:p.Now, at this point, you will inevitably want to actually write some 
data to the output. Here is a handy list containing code chunks for 
:hp2.setting:ehp2. and :hp2.clearing:ehp2. output pins:
:fig width=column place=inline frame=rules.
:p.To set (enable) PB3:
:xmp.
//              3210
GPIOB->ODR |= 0b1000;
:exmp.
:p.To clear (disable) PB3:
:xmp.
//               3210
GPIOB->ODR &= &tilde.0b1000;
:exmp.
:figcap.Setting and clearing PB3 example
:efig.
:h2.Configuring and Using Inputs
:p.First, flip back to :hdref refid=moder. and make sure you pay close 
attention to the :pv.MODER:epv. value to declare a pin as 
input::pk.00:epk.. Of course, you would use the :pv.&=:epv. operation 
to clear those bits. If you forget what this means, go back to 
:hdref refid=bitwise.!
:p.Here is an example that declares PA0 as an input:
:fig width=column place=inline frame=rules.
:xmp.
#include <stm32l4xx.h>
 
void gpiosetup() {
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;   // note: GPIOB
    //   GPIOB pins:   0.
    GPIOB->MODER &= &tilde.0b11;
}
 
int main() {
    gpiosetup();
    while(1) {
        __asm__("wfi");
    }
}
:exmp.
:figcap.PA0 input enablement example
:efig.
:p.In order to actually use these, you can read the :pk.IDR:epk. 
register like so:
:i1.Masking off (bits)
:fig width=column place=inline frame=rules.
:xmp.
if(GPIOA->IDR & 0b1 == 1) {
    // this pin is active
}
else {
    // this pin is not active
}
:exmp.
:figcap.PA0 input reading example
:efig.
:p.Now, you might be asking :q.hey, why are you ANDing the IDR value 
with 1?:eq. Well, you want to :hp5.mask off:ehp5. bits such that you 
only :hp1.get what you want:ehp1. 
:lblbox.Special Pins on GPIOA
:p.:hp2.PA14:ehp2. and :hp2.PA15:ehp2. are special, declared as inputs 
by default, and are used to allow the debugger to communicate with the 
:hp5.ST-LINK:ehp5. chip on the underside of the board (this is the chip 
that drives the USB port). Because one of these is a clock and the 
other one is a data pin, their values jitter erratically and rapidly, 
so you must :hp1.mask off:ehp1. the values you want when you read from 
GPIOA!
:p.:hp3.Never:ehp3. change the :pv.MODER:epv. bits for these!
:elblbox.
:h3 id=pupd.Pull-Up and Pull-Down Resistors
:p.Sometimes, you may wish to use a button that is just 
:hp1.floating:ehp1. 
:fn.This means that the button connects only to voltage or ground, 
rather than being a bi-state button that alternates between connecting 
its output pin to voltage or ground depending on whether or not the 
button is pressed. Basically every button ever made if a floating 
button!
:efn.
with your STM32. To do this and have it work properly, you have to 
employ :hp2.pull-up:ehp2. or :hp2.pull-down:ehp2. resistors or the 
button's value will seem to randomly jitter between on and off!
:fn.This is because static electricity can build up on the 
:hp1.gate:ehp1. of the MOSFETs comprising the :pv.IDR:epv. register, 
causing it to twiddle between 0 and 1.
:efn.
Here's a simple way to know when to use each:
:ul.
:li.If your button is connected to :hp2.ground:ehp2., you will use a 
:hp2.pull-up resistor:ehp2. and watch for when the :pv.IDR:epv. value 
for the pin goes to :pk.0:epk..
:li.If your button is connected to :hp2.voltage:ehp2., you will use a 
:hp2.pull-down resistor:ehp2. and watch for when the :pv.IDR:epv. value 
for the pin goes to :pk.1:epk..
:eul.
:p.It should be clear by now that the pull-up and pull-down resistors 
are :hp2.tiny resistors inside the STM32 package:ehp2. and not physical 
resistors that you have to place anywhere on your breadboard (this 
saves the number of components that you have to physically place on 
your breadboard)!
:note.You can only use pull-up or pull-down resistors when a pin is in 
:hp5.input:ehp5. mode. :hp2.Pull-up and pull-down resistors do nothing 
in output mode!:ehp2.
:p.The following figure shows you how the inside of the STM32 is laid 
out and how those PU/PD resistors are placed and connected:
:fig width=column place=inline frame=rules.
:cgraphic.
                  Vcc
                  &Lh.&Td.&Lh.
                   &Lv.
                  &Ul.&Tu.&Ur.
                  &Lv.P&Lv.
                  &Lv.U&Lv.
                  &Ll.&Td.&Lr.
                   &Lv.
                   &Lv.
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.        &Lv.       &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv. IDR bit &Tr.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tl. Physical pin &Tr.&Lh.&Lh.&Lh.&Ar.
&Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.        &Lv.       &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
                   &Lv.
                   &Lv.
                  &Ul.&Tu.&Ur.
                  &Lv.P&Lv.
                  &Lv.D&Lv.
                  &Ll.&Td.&Lr.
                   &Lv.
                  &Lh.&Tu.&Lh.
                  Gnd
:ecgraphic.
:figcap.STM32 pull-up/pull-down resistor wiring diagram
:efig.
:p.If you recall from :hdref refid=moder., you'll know the general 
:q.two-bits:eq. form of the register. The register we configure to use 
these resistors is :pk.GPIOx->PUPDR:epk..
:fn.:pk.PUPDR:epk. = Pull-Up/Down Register
:efn.
Here is a layout of the register's bits:
:i2.PUPDR
:fig width=column place=inline frame=rules.
:cgraphic.
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv. Px15  &Lv. PxNN  &Lv.  Px1  &Lv.  Px0  &Lv.
&Tr.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Tl.
&Lv. D &Lv. U &Lv. ..... &Lv. D &Lv. U &Lv. D &Lv. U &Lv.
&Ll.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lr.
:ecgraphic.
:figcap.GPIOx_PUPDR layout
:efig.
:p.Given the :pk.D/U:epk. pattern, the following bit patterns are 
possible here:
:table cols='1i 2i'.
:tcap.GPIO PUPDR Bit Patterns
:thd.
:c.:hp2.UD:ehp2.
:c.:hp2.Mode:ehp2.
:ethd.
:row split=yes.
:c.:pk.00:epk.
:c.Neither pull-up nor pull-down
:row split=yes.
:c.:pk.01:epk.
:c.Pull-up
:row split=yes.
:c.:pk.10:epk.
:c.Pull-down
:row split=yes.
:c.:pk.11:epk.
:c.Both (impossible state, do not use!)
:etable.
:p.To actually use these, you can write something like this:
:fig width=column place=inline frame=rules.
:xmp.
#include <stm32l4xx.h>
 
void pupdsetup() {
    //   GPIOA pins:   1.0.
    GPIOA->PUPDR &= &tilde.0b1111; // clear the bits first
    GPIOA->PUPDR |=  0b1001; // PA0 = PU, PA1 = PD
}
 
void gpiosetup() {
    ...
}
 
int main() {
    gpiosetup();
    pupdsetup();
    while(1) {
        __asm__("wfi");
    }
}
:exmp.
:figcap.PA0 and PA1 pull-up and pull-down example
:efig.
:p.Now, use the pins as inputs!
:lblbox.Pull-up Voltage Leakage
:p.Did you know that you can actually somewhat use the pull-up and 
pull-down resistors as a way of tricking a pin declared as input to 
provide outputs?
:p.You can engage the pull-up to output a logic 1, and engage the 
pull-down to output a logic 0.
If you use this technique, make sure you have one or the other, but not 
both or neither, to prevent floating pins!
:p.This may sound like useless information, but using the pull-up 
resistors as outputs becomes very important if you need to drive a 
:hp1.keypad:ehp1. or any such similar device!
:elblbox.
:h2 id=altfnc.Alternate Function Mode
:p.Sometimes, you may wish to use all sorts of :q.fancy:eq. peripherals 
like:
:i2.AF/AFR
:ul.
:li.Timers to generate PWM (see :hdref refid=pwm.)
:li.Serial ports:
:ul.
:li.UART (i.e. :q.asynchronous serial:eq.)
:li.SPI
:fn.Serial Peripheral Interface is :hp5.heavily:ehp5. used to drive SD 
cards, external sensors, serial RAM and ROM chips, debuggers from other 
manufacturers besides ST, and things like that!
:efn.
:li.I&sup2.C
:li.CAN
:fn.Controller Area Network is the serial bus often used in cars.
:efn.
:eul.
:li.Timers to generate PWM (see :hdref refid=pwm.)
:li.USB
:eul.
:p.You need to engage :hp2.alternate function:ehp2. mode to set these 
up. This requires you to do :hp1.two:ehp1. things:
:ol.
:li.Find the bits in :pk.GPIOx->MODER:epk. and set them to :pk.10:epk. 
like we covered in :hdref refid=moder.
:li.Use the :hp1.correct:ehp1. :pk.GPIOx->AFR&lbrk.y&rbrk.:epk. to 
select which alternate function you want for the pins you selected in 
the mode register
:eol.
:p.The :pk.AFR:epk. register is very strange, because each I/O pin can 
have up to :hp3.16:ehp3. alternate functions!
If you recall from Digital Logic Circuits class, you'll know that in 
order to count to 16 in binary (so, 0 to 15), you'll need :hp5.3:ehp5. 
bits. That means that the :pk.AFR:epk. register is :hp1.wider:ehp1. 
than :pk.MODER:epk., which will result in it being broken into multiple 
chunks as an :hp5.array.:ehp5.
:note.I say that each pin can be bound to one of 15 different alternate 
functions, but the STM32L4 and STM32F4 series boards that you will 
frequently encounter only provide :hp3.8:ehp3. alternate functions 
(that is, AF0 through AF7).
:p.Now, because there are 4 bits per pin, that means there are 
:hp1.two:ehp1. AFRs. The STM32 manuals refer to those as 
:pv.GPIOx_AFRL:epv. and :pv.GPIOx_AFRH:epv., but this isn't what you'll 
refer to them as in your C program; here is a handy table that explains 
the mapping:
:table cols='* * *'.
:tcap.GPIO AFRL/ARFH Mapping
:thd.
:c.:hp2.Bits:ehp2.
:c.:hp2.STM32 Manual Name:ehp2.
:c.:hp2.C Program Name:ehp2.
:ethd.
:row split=yes.
:c.Px0 through Px7
:c.:pv.GPIOx_AFRL:epv.
:c.:pk.GPIOx->AFR&lbrk.0&rbrk.:epk.
:row split=yes.
:c.Px8 through Px15
:c.:pv.GPIOx_AFRH:epv.
:c.:pk.GPIOx->AFR&lbrk.1&rbrk.:epk.
:etable.
:p.So, as you can see, it's split in two in the middle and is accessed 
like an array. Now, let us examine the layout of those two registers:
:fig width=column place=inline frame=rules.
:cgraphic.
GPIOx_AFRL:
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv.      Px7      &Lv.         &Lv.      Px0      &Lv.
&Tr.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Tl.
&Lv. D &Lv. C &Lv. B &Lv. A &Lv.         &Lv. D &Lv. C &Lv. B &Lv. A &Lv.
&Ll.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lr.
31                                        0
 
GPIOx_AFRH:
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv.      Px15     &Lv.         &Lv.      Px8      &Lv.
&Tr.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Tl.
&Lv. D &Lv. C &Lv. B &Lv. A &Lv.         &Lv. D &Lv. C &Lv. B &Lv. A &Lv.
&Ll.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lr.
31                                        0
:ecgraphic.
:figcap.GPIOx_AFRL and AFRH layout
:efig.
:p.The :pv.DCBA:epv. pattern is a :hp5.4-bit binary number:ehp5., so, 
if you want to select alternate function 3, you would set :pv.DCBA:epv. 
to :pv.0011:epv..
:note.In order to figure out :hp5.what the AF mappings are for each 
pin:ehp5., you will need to check the corresponding :hp1.device 
datasheet:ehp1.; see :hdref refid=biblio. for more information.
:p.Now, let us examine an example program that engages AF7 on PA9 and 
AF7 on PA10.
:fn.This enables the :pv.USART1:epv. interface; PA9 is transmit, and 
PA10 is receive. Using serial ports may be useful in your Capstone 
project!
:efn.
:fig width=column place=inline frame=rules.
:xmp.
// set PA9 and PA10 as AF; clear the interested bits first
GPIOA->MODER &= &tilde.0b1111000000000000000000;
GPIOA->MODER |=  0b101000000000000000000000;
// AFR bits:        10..9...8...
GPIOA->AFR&lbrk.1&rbrk. &= &tilde.0b111111110000;
GPIOA->AFR&lbrk.1&rbrk. |=  0b011101110000;
:exmp.
:figcap.PA9 and PA10 alternate function definition example
:efig.
:p.Now, what you end up doing with this alternate function is up to 
you! You will certainly use PWM in one of the lab assignments, so check 
:hdref refid=pwm. for more information on that.
:h2 id=analog.Analog Mode
:p.One of the other modes you can put a GPIO mode into is :hp2.analog 
mode.:ehp2. This is specifically used for the :hp2.ADC:ehp2., which we 
will cover later; turn to :hdref refid=adc. for more information.
:p.To set a pin into analog mode, write :pk.01:epk. to the 
corresponding :pv.MODER:epv. bits!
:i2.Analog mode
:h1.Interrupts
:p.One of the most useful things you will ever encounter in the world 
of computing is that of the :hp2.interrupt.:ehp2. The purpose of an 
interrupt is to :hp1.temporarily stop the execution of a program, jump 
to a certain function, run some code, and return back to where you left 
off:ehp1. when :hp1.an input event or software trigger occurs.:ehp1.
:p.In the world of embedded systems, an :q.input event:eq. can be a 
button press, timer counter limit hit, data coming in over a serial 
interface, or a system interval timer; a :q.software trigger:eq. only 
really occurs when you are running a real operating system.
:fn.For those curious and for those who did not pay much attention in 
Operating Systems class, a :hp5.system call:ehp5. is implemented using 
an interrupt that your user programs :q.simulate:eq. using some kind of 
CPU instruction.
:efn.
:p.This section will cover interrupts as they relate to push buttons 
and other such momentary inputs; we will not be debouncing the button 
or anything with this code!
:p.Let us connect a push button to PA1. We will connect it like this:
:fig width=column place=inline frame=rules.
:p.Using the WaveForms board:
:cgraphic.
BTN1 &Al.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ar. PA1
:ecgraphic.
:p.Using a real button:
:cgraphic.
VCC
&Lh.&Td.&Lh.
 &Lv.
 &Lv.
 &Lv.        &Lv.
 &Lv.      &Lh.&Lh.&Tu.&Lh.&Lh.
 &Lv.      &Au.   &Au.
 &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.   &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ar. PA1
:ecgraphic.
:figcap.Button on PA1
:efig.
:note.If you are following this section to configure interrupts for 
your lab assignment(s), you will want to use the :hp1.first:ehp1. 
circuit wherein you use the :pk.BTN1:epk. output of the WaveForms board 
and wire it straight into PA1 on your STM32.
:p.:warning.Make sure all of the voltage switches on your WaveForms 
board are up; these are located at the top right of the white portion 
of the breadboard, the part that you take out of the board and take 
home after every lab!:ewarning.
:p.Now that you've decided that you want to use PA1, you need to do the 
following things to actually enable and use the interrupt:
:ol.
:li.Configure the GPIO pin that the button is wired to (PA1) as an 
input.
:li.If you are using a real button, enable the :hp1.pull-down 
resistor:ehp1. on PA1.
:fn.See :hdref refid=pupd. for help with this!
:efn.
:li.Determine which EXTI interrupt line you need to enable in the NVIC.
:li.Set the flags for the EXTI line (:pk.FTSR1:epk., :pk.PR1:epk., and 
:pk.IMR1:epk.) for a falling-edge-triggered interrupt.
:li.Enable the EXTI IRQ in the NVIC.
:fn.Nested Vectored Interrupt Controller
:efn.
:li.Write an IRQ handler function.
:eol.
:note.You covered all of this back in ELEC 2220!
:h2.Understanding the NVIC
:p.Before we proceed, it is very helpful to know how exactly the 
:hp2.NVIC:ehp2. 
:fn.Nested Vectored Interrupt Controller
:efn.
works for the EXTI interrupts. See the following diagram for an example 
of how each GPIO pin results in an EXTI interrupt being generated:
:fig width=column place=inline frame=rules.
:artwork name=nvicexti.
:figcap.NVIC EXTI flow
:efig.
:p.As you can see, all of the GPIO pins numbered 0 can result in the 
production of the :pv.EXTI0:epv. interrupt. This means that PC3 would 
result in the production of the :pv.EXTI3:epv. interrupt, and PA1 will 
result in the production of :pv.EXTI1:epv..
:p.It should be noted that there are :hp1.many:ehp1. other interrupts 
the NVIC provides:
:ul.
:li.Core CPU interrupts: faults, system service call (SVC), the SysTick 
timer, non-maskable interrupt (NMI)
:li.External interrupts (EXTI) -- :hp1.covered in this section:ehp1.
:li.The STM peripherals:
:ul.
:li.DMA completion interrupts
:li.Timers (see :hdref refid=timers.)
:li.Serial interface controllers: SPI, I&sup2.C, CAN, USB
:li.ADC completion interrupts (see :hdref refid=adc.)
:li.DAC completion interrupts
:eul.
:eul.
:p.In this chapter, we are only looking at the EXTI interrupts!
:h2.Configuring Input Interrupts
:p.Now that you understand the NVIC, let us proceed!
:h3.Configuring the EXTICR Register
:p.Before we can configure the interrupt properties of PA1, we must 
first enable it in the :pk.SYSCFG->EXTICR:epk. register. This, much in 
the same way the :pk.GPIOx->AFR:epk. register, is split into two. Just 
like the :pv.AFR:epv. register, each entry comprises :hp2.4:ehp2. bits 
(but only :hp2.3:ehp2. of which are actually used). There are a total 
of :hp2.4:ehp2. :pv.EXTICR:epv. registers, laid out as follows:
:fig width=column place=inline frame=rules.
:cgraphic.
SYSCFG_EXTICR1:
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv.      Px7      &Lv.         &Lv.      Px0      &Lv.
&Tr.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Tl.
&Lv. x &Lv. C &Lv. B &Lv. A &Lv.         &Lv. x &Lv. C &Lv. B &Lv. A &Lv.
&Ll.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lr.
15                   .                    0
                     .
                     .
 
SYSCFG_EXTICR4:
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv.      Px15     &Lv.         &Lv.      Px8      &Lv.
&Tr.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Tl.
&Lv. D &Lv. C &Lv. B &Lv. A &Lv.         &Lv. D &Lv. C &Lv. B &Lv. A &Lv.
&Ll.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh./&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lr.
15                                        0
:ecgraphic.
:figcap.SYSCFG_EXTICRx register layout
:efig.
:note.Only bits 0 to 15 are used in these registers, and the :pk.x:epk. 
means the bit is :q.dead:eq. and does not do anything!
:p.Here is a handy table that maps the four registers to their STM32 
manual name and C program variable name:
:table cols='* * *'.
:tcap.EXTICRx Mapping
:thd.
:c.:hp2.EXTI:ehp2.
:c.:hp2.STM32 Manual Name:ehp2.
:c.:hp2.C Program Name:ehp2.
:ethd.
:row split=yes.
:c.0 through 3
:c.:pv.SYSCFG_EXTICR1:epv.
:c.:pk.SYSCFG-&gtsym.EXTICR&lbrk.0&rbrk.:epk.
:row split=yes.
:c.4 through 7
:c.:pv.SYSCFG_EXTICR2:epv.
:c.:pk.SYSCFG-&gtsym.EXTICR&lbrk.1&rbrk.:epk.
:row split=yes.
:c.8 through 11
:c.:pv.SYSCFG_EXTICR3:epv.
:c.:pk.SYSCFG-&gtsym.EXTICR&lbrk.2&rbrk.:epk.
:row split=yes.
:c.12 through 15
:c.:pv.SYSCFG_EXTICR4:epv.
:c.:pk.SYSCFG-&gtsym.EXTICR&lbrk.3&rbrk.:epk.
:etable.
:p.So, there are two ways to populate the bits of the :pv.EXTICR:epv. 
register you need to write to (which, for our PA1 interrupt, is 
:pk.SYSCFG->EXTICR 0¡:epk.):
:ol.
:li.By directly writing the bits
:li.Using the macro bitmask names
:fn.These are defined in :pv.stm32l4xx.h:epv.; you can right-click any 
of these terms after typing them in STM32CubeIDE and click the :q.Go to 
Definition:eq. button to see what these resolve to (with binary 
immediate or bit-shift patterns).
:efn.
 
:eol.
:p.Here is a sample of both:
:i1.EXTICR
:fig width=column place=inline frame=rules.
:xmp.
// using macro bitfield names; clearing first, then selecting PA
SYSCFG->EXTICR&lbrk.0&rbrk. &= &tilde.SYSCFG_EXTICR1_EXTI1;
SYSCFG->EXTICR&lbrk.0&rbrk. |= SYSCFG_EXTICR1_EXTI1_PA;
// using bits directly:
SYSCFG->EXTICR&lbrk.0&rbrk. &= &tilde.0b01110000;
SYSCFG->EXTICR&lbrk.0&rbrk. |= 0b00010000;
:exmp.
:figcap.EXTICR PA1 selection example
:efig.
:note.Make sure PA1 has been declared as an input :hp1.before:ehp1. 
proceeding (see :hdref refid=moder. for a refresher on this).
:h3.Setting the Interrupt Flags
:p.At this point, the SYSCFG module has :q.routed:eq. the line from PA1,
:fn.Please note that both the SYSCFG module enables and disables which 
pins can connect to interrupts; the EXTI module connects PA1 to the 
NVIC itself.
:efn.
but we have not yet selected a rising-edge or falling-edge interrupt; 
likewise, we have not connected the EXTI block to the NVIC -- we have 
also not cleared the Pending Interrupt Flag that will raise the moment 
the interrupt is enabled. We will connect it after this.
:p.There are a number of registers in the :pk.EXTI:epk. struct that we 
are interested in:
:i1.EXTI
:i2.FTSR/RTSR
:i2.PIF
:i2.IMR/EMR
:table cols='1i *'.
:thd.
:c.:hp2.Register:ehp2.
:c.:hp2.Description:ehp2.
:ethd.
:row split=yes.
:c.:pk.EXTI->IMR1:epk.
:c.:hp1.Interrupt Mask Register,:ehp1. which connects and
disconnects the GPIO pin to the NVIC line
:row split=yes.
:c.:pk.EXTI->EMR1:epk.
:c.:hp1.Event Mask Register,:ehp1. which completely disables
event and interrupt generation (by default, every event is
:hp5.enabled:ehp5.)
:row split=yes.
:c.:pk.EXTI->RTSR1:epk.
:c.:hp1.Rising Trigger Selection Register,:ehp1. which enables
rising-edge interrupts for each GPIO line
:row split=yes.
:c.:pk.EXTI->FTSR1:epk.
:c.:hp1.Falling Trigger Selection Register,:ehp1. which enables
falling-edge interrupts for each GPIO line
:row split=yes.
:c.:pk.EXTI->SWIER1:epk.
:c.:hp1.Software Interrupt Event Register,:ehp1. wherein writing
a bit to the correct slot will result in the generation of an
interrupt by your program
:row split=yes.
:c.:pk.EXTI->PR1:epk.
:c.:hp1.Pending Register,:ehp1. wherein writing a 1 to the correct
slot :q.dismisses:eq. an interrupt (you will need to do this in your
IRQ handler function)
:etable.
:note.Just like there is an :pk.FTSR1:epk., there is also an 
:pk.FTSR2:epk. for additional interrupts -- you won't be using this, 
though!
:p.These registers are laid out as follows:
:fig width=column place=inline frame=rules.
:cgraphic.
EXTI_RTSR1:
&Ul.&Lh.&Lh.&Lh.&Td.&Lh./&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ur.
&Lv. 31| / &Lv. 3 | 2 | 1 | 0 &Lv. Interrupt Number
&Tr.&Lh.&Lh.&Lh.&Ju.&Lh./&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Tl.
&Lv. E &Lv. / &Lv. E &Lv. E &Lv. E &Lv. E &Lv.
&Ll.&Lh.&Lh.&Lh.&Tu.&Lh./&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lr.
31                      0
 
EXTI_FTSR1:
&Ul.&Lh.&Lh.&Lh.&Td.&Lh./&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ur.
&Lv. 31| / &Lv. 3 | 2 | 1 | 0 &Lv.
&Tr.&Lh.&Lh.&Lh.&Ju.&Lh./&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Tl.
&Lv. E &Lv. / &Lv. E &Lv. E &Lv. E &Lv. E &Lv.
&Ll.&Lh.&Lh.&Lh.&Tu.&Lh./&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lr.
31                      0
 
EXTI_IMR1:
&Ul.&Lh.&Lh.&Lh.&Td.&Lh./&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ur.
&Lv. 31| / &Lv. 3 | 2 | 1 | 0 &Lv.
&Tr.&Lh.&Lh.&Lh.&Ju.&Lh./&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Tl.
&Lv. E &Lv. / &Lv. E &Lv. E &Lv. E &Lv. E &Lv.
&Ll.&Lh.&Lh.&Lh.&Tu.&Lh./&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lr.
31                      0
 
EXTI_PR1:
&Ul.&Lh.&Lh.&Lh.&Td.&Lh./&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ur.
&Lv. 31| / &Lv. 3 | 2 | 1 | 0 &Lv.
&Tr.&Lh.&Lh.&Lh.&Ju.&Lh./&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Tl.
&Lv. E &Lv. / &Lv. E &Lv. E &Lv. E &Lv. E &Lv.
&Ll.&Lh.&Lh.&Lh.&Tu.&Lh./&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lr.
31                      0
 
:ecgraphic.
:figcap.EXTI register layouts
:efig.
:p.So, if we want a :hp1.falling-edge interrupt,:ehp1. you will need to 
alter :pk.EXTI->FTSR1:epk., :pk.EXTI->PR1:epk., and :pk.EXTI->IMR1:epk.
:p.Here is some code that will do that:
:fig width=column place=inline frame=rules.
:xmp.
EXTI->FTSR1 |= EXTI_FTSR1_FT1;
EXTI->PR1 |= EXTI_PR1_PIF1;
EXTI->IMR1 |= EXTI_IMR1_IM1;
:exmp.
:figcap.PA1 interrupt flags configuration example
:efig.
:p.For PA5, you would replace the last number before the semicolon with 
5, so, :pk.EXTI_FTSR1_FT5:epk..
:h3.Enabling the Interrupt in the NVIC
:p.Next, you need to use two macro-functions
:fn.These are functions defined with the :pk.inline:epk. keyword; you 
can learn about that by reading :hdref refid=inline..
:efn.
to tell the NVIC to unblock the path from the EXTI block to the NVIC 
block:
:fig width=column place=inline frame=rules.
:xmp.
NVIC_ClearPendingIRQ(EXTI1_IRQn);
NVIC_EnableIRQ(EXTI1_IRQn);
:exmp.
 
:figcap.NVIC interrupt enablement example
:efig.
:p.This part is fairly simple! Note that the syntax of this really does 
say :pk.EXTI1_IRQn:epk.; you can see the :pk.1:epk. there is the 
variable part, so if you were using an interrupt on PB6, you would use 
:pk.EXTI6_IRQn:epk.. Before the program can run, though, you must run 
one more function to enable :hp1.all:ehp1. interrupts on the CPU 
globally:
:fig width=column place=inline frame=rules.
:p.Using the C function:
:xmp.__enable_irq();
:exmp.
:p.Using inline assembly:
:xmp.__asm__("cpsie i");
:exmp.
 
:figcap.Global interrupt enablement
:efig.
:note.There are :hp3.two underscores:ehp3. on both of those (except the 
single underscore for :pk.enable_irq:epk.)!!
:h3.Writing the ISR
:p.Now that the interrupt can (in theory) fire, you need to write a 
function that the CPU will jump to. This is our :hp2.interrupt service 
routine:ehp2., or ISR for short. These have a :hp5.specific:ehp5. name 
that you cannot deviate from (see the info-box after the code sample 
for an explanation as to why this is the case)!
:i1.ISR
:p.Since we are using :pv.EXTI1:epv. because we want PA1 to be our 
interrupt pin, we have to write a function named 
:pk.EXTI1_IRQHandler:epk. and it will have a :pv.void:epv. return type.
:p.Here is the general form of an EXTI ISR:
:fig width=column place=inline frame=rules.
:xmp.
#include <stm32l4xx.h>
void gpiosetup() {
 
void EXTI1_IRQHandler() {
    NVIC_ClearPendingIRQ(EXTI1_IRQn); // flush pending interrupts
    // do something here with your button...
    EXTI->PR1 |= EXTI_PR1_PIF1;       // we have processed the IRQ
}
:exmp.
 
:figcap.EXTI IRQ handler function example
:efig.
:p.At this point, you're done! After the info-box, I will provide you 
with a complete code sample for more than one interrupt in case you 
think you forgot something.
:lblbox.How are the IRQ Handler Functions Accessed?
:p.In your :pk.startup_devicename.s:epk. file (provided by the 
STM32Cube development toolchain), there is a :hp1.function vtable:ehp1. 
consisting of an array of function pointers (see :hdref refid=fnptr.) 
stored at a very specific memory address.
:p.When the EXTI1 interrupt comes in, the CPU will convert that into a 
numeric index to that function pointer array, extract that memory 
address, and then jump into that function (after saving the return 
address it needs to get back to what it was doing beforehand).
:p.Each interrupt source has an assigned number for each interrupt 
entry in the IRQ function pointer table!
:elblbox.
:h3.Summary and Complete Example
:p.This enables PA1 and PA2 as interrupts. This example is long, so 
turn the page to see it on the back (to avoid having to flip the page 
over and over to read it all at the same time):
:fig width=column place=inline frame=rules.
:xmp keep=5.
#include <stm32l4xx.h>
 
void gpiosetup() {
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
    GPIOA->MODER &= &tilde.0b1111; // clear for input
}
 
void intsetup() {
    // EXTICR input selection
    SYSCFG->EXTICR&lbrk.0&rbrk. &= &tilde.SYSCFG_EXTICR1_EXTI1;
    SYSCFG->EXTICR&lbrk.0&rbrk. |= SYSCFG_EXTICR1_EXTI1_PA;
    SYSCFG->EXTICR&lbrk.0&rbrk. &= &tilde.SYSCFG_EXTICR1_EXTI2;
    SYSCFG->EXTICR&lbrk.0&rbrk. |= SYSCFG_EXTICR1_EXTI2_PA;
    // flag configuration
    EXTI->FTSR1 |= EXTI_FTSR1_FT1;
    EXTI->PR1 |= EXTI_PR1_PIF1;
    EXTI->IMR1 |= EXTI_IMR1_IM1;
    EXTI->FTSR1 |= EXTI_FTSR1_FT2;
    EXTI->PR1 |= EXTI_PR1_PIF2;
    EXTI->IMR1 |= EXTI_IMR1_IM2;
    // NVIC enablement
    NVIC_ClearPendingIRQ(EXTI1_IRQn);
    NVIC_EnableIRQ(EXTI1_IRQn);
    NVIC_ClearPendingIRQ(EXTI2_IRQn);
    NVIC_EnableIRQ(EXTI2_IRQn);
    // enable interrupts
    __enable_irq();
}
 
void EXTI1_IRQHandler() {
    NVIC_ClearPendingIRQ(EXTI1_IRQn); // flush pending interrupts
    // do something here with your button...
    EXTI->PR1 |= EXTI_PR1_PIF1; // we have processed the IRQ
}
 
void EXTI2_IRQHandler() {
    NVIC_ClearPendingIRQ(EXTI2_IRQn); // flush pending interrupts
    // do something here with your button...
    EXTI->PR1 |= EXTI_PR1_PIF2; // we have processed the IRQ
}
 
int main() {
    gpiosetup();
    intsetup();
    while(1) {
        __asm__("wfi");
    }
}
:exmp.
 
:figcap.Complete EXTI GPIO example
:efig.
:h1 id=timers.Timers
:p.Sometimes, you want to provide repeating events
:fn.i.e. interrupts
:efn.
to a computer. Some of these cases may look like this:
:ul.
:li.Take a reading from a sensor
:li.Check to see if an asynchronous operation has completed
:li.Measure how long something is taking
:li.Generate a PWM signal (this will be covered later; see 
:hdref refid=pwm.)
:eul.
:h2.Understanding the Timers
:p.The STM32 has several programmable timers, which will 
:hp5.count:ehp5. based on one of two different inputs:
:i1.Timers
:ol.
:li.An oscillator clock signal
:fn.This will be derived by a :hp2.clock divider:ehp2., which will be 
covered when we discuss the :hp1.prescaler:ehp1..
:efn.
:li.Some kind of repeating event
:fn.Like button presses. Note that not all of the timers can be 
connected to an arbitrary input pin and instead must be connected to a 
clock like option #1!
:efn.
:eol.
:h4 id=timevt.Event Types
:p.So, you have two :hp5.event sources:ehp5. and those pulses will 
increment a (pre-settable) counter. Once the counter reaches a 
:hp5.threshold value:ehp5. (called the :hp2.autoreload value:ehp2.), 
one of two things will happen:
:i2.Event types
:ol.
:li.The counter will be zeroed
:li.An event will be generated:
:ul.
:li.A :q.counter full:eq. flag will be set (this can be checked by your 
code)
:li.An interrupt will fire (you do need to dismiss the :q.counter 
full:eq. flag, though)
:li.The output state of an I/O pin will toggle
:fn.This is PWM mode, which will be covered next; see :hdref refid=pwm..
:efn.
:eul.
:eol.
:note.Some timers can count upwards :hp1.and:ehp1. downwards!
:h3.STM32L4xx Timers
:p.The following timers are present on the STM32L432xxx board:
:table cols='1i 0.5i 1i 1i' id=timtbl.
:tcap.STM32L432xxx Timers
:thd.
:c.:hp2.Timer:ehp2.
:c.:hp2.Bits:ehp2.
:c.:hp2.Direction:ehp2.
:c.:hp2.Channels:ehp2.
:ethd.
:row split=yes.
:c.:pv.TIM1:epv.
:c.16
:c.up/down
:c.4
:row split=yes.
:c.:pv.TIM2:epv.
:c.32
:c.up/down
:c.4
:row split=yes.
:c.:pv.TIM3:epv.
:c.32
:c.up/down
:c.4
:row split=yes.
:c.:pv.TIM6:epv.
:c.16
:c.up
:c.0
:row split=yes.
:c.:pv.TIM7:epv.
:c.16
:c.up
:c.0
:row split=yes.
:c.:pv.TIM15:epv.
:c.16
:c.up
:c.2
:row split=yes.
:c.:pv.TIM16:epv.
:c.16
:c.up
:c.1
:row split=yes.
:c.SysTick
:c.24
:c.up
:c.0
:row split=yes.
:c.:pv.LPTIM1:epv.
:c.16
:c.up
:c.0
:row split=yes.
:c.:pv.LPTIM2:epv.
:c.16
:c.up
:c.0
:etable.
:note.The :pv.LPTIMx:epv. timers are :hp5.low-power timers:ehp5. that 
can run while the CPU is stalled (as such, they are capable of 
restarting the CPU while it's powered down).
:i2.Standard timers (TIMx)
:i2.Low-power timer (LPTIMx)
:i2.SysTick timer
:p.The :hp2.channel:ehp2. is what defines the function of a timer when 
it is being used for something :hp1.besides:ehp1. interrupt generation.
The channels can be set to one of three modes:
:i2.Channel
:i3.Input capture
:i3.Output compare
:ol.
:li.Input capture (counting button presses, for example)
:li.Output compare (triggering an interrupt when the counter counts to 
a certain value, for example
:li.PWM (generating a pseudo-analog waveform)
:eol.
:h3 id=clock.Clock Division: SYSCLK and PSC/AAR
:p.Unless you have connected a timer's input to an input pin (in input 
capture mode), you will need to utilize a :hp2.clock divider:ehp2. to 
provide an input event source. As you might imagine, the clock divider 
is dividing the :hp2.master system clock.:ehp2. 
:i2.Clock divider
:p.In order to derive a timer frequency, you must set two things:
:ol.
:li.The system master clock, :pk.SYSCLK:epk.
:li.The prescaler for the timer, :pk.TIMx->PSC:epk.
:li.While it does not alter the timer frequency: the autoreload 
register, :pk.TIMx->ARR:epk. 
:fn.The ARR doesn't alter the timer's frequency, but it does control 
what the :q.trigger value:eq. the timer must count up to before 
something happens.
:efn.
:eol.
:i3.SYSCLK
:i3.PSC
:i3.ARR
:p.Now, SYSCLK can be derived from four different sources:
:ol.
:li.:hp2.MSI:ehp2. (multi-speed internal): a 100 kHz to 48 MHz clock, 
:hp5.defaults to 4 MHz unless otherwise changed:ehp5.
:p.This is the SYSCLK mode we will be using; you do not have to do 
anything to engage it or alter it.
:li.:hp2.HSI:ehp2. (high-speed internal): 16 MHz
:p.To enable this, you must do:
:xmp.
RCC->CR |= RCC_CR_HSION;               // power it up
while((RCC->CR & RCC_CR_HSIRDY) == 0); // wait for readiness
RCC->CFGR |= RCC_CFGR_SW_HSI;          // SYSCLK is now HSI
:exmp.
:li.:hp2.HSE:ehp2. (high-speed external): 4 MHz to 48 MHz
:p.This requires you to connect a clock signal of some kind to pin PA0; 
this signal can be generated by a signal generator in a lab, a 
crystal-oscillator clock generator chip, or a monolithic square-wave 
crystal oscillator pagkage.
:li.:hp2.PLL:ehp2. (phase-locked loop): multiplies one of the above 
clocks by some factor (permits :hp2..clock scaling:ehp2. in software)
:eol.
:p.For our 3040/3050 projects, we will just use the MSI clock and let 
it run at its default 4 MHz. Now, the timers' inputs then run through 
the :hp2.prescaler:ehp2. and then into the counter; whenever the 
:hp2.autoreload register:ehp2. value equals the counter value, an event 
will be generated
:fn.Remember, these are shown on :hdref refid=timevt..
:efn.
:p.The following picture shows the :q.wiring:eq. of this system:
:fig width=column place=inline frame=rules.
:cgraphic.
             CK_INT      &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
TIMxCLK &Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ar.&Lv.  Trigger   &Lv.
        (internal clock) &Lv. Controller &Lv.
                         &Ll.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
                           &Lv.                        &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
    &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.                   &Ul.&Lh.&Lh.&Lh.&Ar.&Lv. Flag &Lv.
    &Lv.                                          &Lv.    &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
    &Lv.     &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.     &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.        &Lv.
    &Ll.&Lh.&Lh.&Lh.&Lh.&Ar.&Lv. Prescaler &Tr.&Lh.&Lh.&Lh.&Lh.&Ar.&Lv. Counter &Tr.&Lh.&Lh.&Lh.&Lh.&Ar. Event &Lh.&Lh.&Lh.&Ur.
          &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.     &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.               &Lv.
                                 &Au.                    &Lv.
                                 &Lv.                    &Lv.
          &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.     &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.         &Lv.
          &Lv. UIE &Lv.     &Lv. Autoreload Register &Lv.         &Lv.
          &Ll.&Lh.&Lh.&Td.&Lh.&Lh.&Lr.     &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.         &Lv.
             &Ad.      &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.                           &Lv.
      &Ul.&Lh.&Lh.&Lh.&Lh. AND &Al.&Lh.&Lh.&Lh.&Tl. UIF &Tr.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
      &Lv.             &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
      &Ad.
  Interrupt
:ecgraphic.
:figcap.TIMx wiring diagram
:efig.
:h2.Using Timers for Interrupts
:p.Before we can actually program any of the timers, we have to first 
enable them -- that requires you to set the correct bit in either 
:pk.RCC->APB1ENR1:epk. or :pk.RCC->APB2ENR:epk.. Here is a table of 
what bit name you would set to :pv.1:epv. with the necessary C 
statements listed:
:i2.Enabling (APB1/APB2 register)
:table id=timenb cols='1i 3i'.
:tcap.TIMx Enablement Statements
:thd.
:c.:hp2.Timer:ehp2.
:c.:hp2.C Statement:ehp2.
:ethd.
:row split=yes.
:c.:pv.TIM1:epv.
:c.:pk.RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;:epk.
:row split=yes.
:c.:pv.TIM2:epv.
:c.:pk.RCC->APB1ENR1 |= RCC_APB1ENR1_TIM2EN;:epk.
:row split=yes.
:c.:pv.TIM3:epv.
:c.:pk.RCC->APB1ENR1 |= RCC_APB1ENR1_TIM3EN;:epk.
:row split=yes.
:c.:pv.TIM6:epv.
:c.:pk.RCC->APB1ENR1 |= RCC_APB1ENR1_TIM6EN;:epk.
:row split=yes.
:c.:pv.TIM7:epv.
:c.:pk.RCC->APB1ENR1 |= RCC_APB1ENR1_TIM7EN;:epk.
:row split=yes.
:c.:pv.TIM15:epv.
:c.:pk.RCC->APB2ENR |= RCC_APB2ENR_TIM15EN;:epk.
:row split=yes.
:c.:pv.TIM16:epv.
:c.:pk.RCC->APB2ENR |= RCC_APB2ENR_TIM16EN;:epk.
:row split=yes.
:c.:pv.LPTIM1:epv.
:c.:pk.RCC->APB1ENR1 |= RCC_APB1ENR1_LPTIM1EN;:epk.
:row split=yes.
:c.:pv.LPTIM2:epv.
:c.:pk.RCC->APB1ENR2 |= RCC_APB1ENR2_LPTIM2EN;:epk.
:etable.
:note.See :tref refid=timtbl. for the bitness and counting direction 
associated with the timers if you flipped to this table from the ToC or 
index!
:lblbox.What Timers are for What?
:p.Not all the timers are equal! Some of them are generally used for 
different purposes, like so:
:dl.
:dthd.Timer
:ddhd.Usage
:dt.:pv.TIM1:epv. 
:dd.Synchronizing the ADC, interfacing with specific sensors, producing 
multi-phase PWM signals
:dt.:pv.TIM2/3:epv. 
:dd.PWM, high-accuracy interrupts, sampling input clock signals
:dt.:pv.TIM6/7:epv. 
:dd.Low-accuracy interrupts (decade counters, slow interval timers)
:dt.:pv.TIM15:epv. 
:dd.Sampling the PWM of an input signal, high-accuracy interrupts
:dt.:pv.TIM16:epv. 
:dd.High-accuracy interrupts
:dt.:pv.LPTIM1/2:epv. 
:dd.Wakeup timers while the CPU is powered down
:dt.SysTick
:dd.Operating system scheduler jiffy (timeslice) n
:edl.
:p.Note that the :hp2.SysTick:ehp2. timer channel is special -- it is a 
built-in ARM Cortex-M CPU peripheral and not an STM peripheral like all 
of the rest on this list!
:elblbox.
:p.After you enable the timer block in the APB register that 
corresponds to the timer in question, you need to set the 
:hp2.prescaler.:ehp2. There is a formula that is very handy here to 
help you derive the correct (16-bit) prescaler value:
:i2.Setting PSC
:fig width=column place=inline frame=rules.
:df align=center.
F sub <CK_CNT> = <F sub <CK_PSC>> over <PSC + 1>
:edf.
:figcap.TIMx->PSC formula
:efig.
:p.Remember, by default, :f.F sub CK_CNT:ef. is 4 MHz! Knowing this, 
you can solve for the prescaler value you want. Since we want to 
trigger :hp5.interrupts,:ehp5. you need to also set the :hp2.autoreload 
register.:ehp2. The formula to calculate this depends on the previous 
formula's output value, and is as follows:
:fig width=column place=inline frame=rules.
:df align=center.
T sub out = <(ARR + 1) * (PSC + 1)> over <F sub CK_PSC>
= <(ARR + 1)> over <F sub CK_CNT>
:edf.
:figcap.TIMx->PSC formula
:efig.
:note.You will likely want to use the :hp1.second:ehp1. equated 
function (the right-most one), because you can omit the prescaler for 
faster clocks (which will be useful when you do :hp2.PWM:ehp2.).
:h3.Enabling the Timer
:p.To actually enable your timer, you would simply use one of the lines 
from :tref refid=timenb. like so (for TIM6), and also set 
:pk.TIMx->PSC:epk. alongside :pk.TIMx->ARR:epk.:
:fig width=column place=inline frame=rules.
:xmp.
void timersetup() {
    RCC->APB1ENR1 |= RCC_APB1ENR1_TIM6EN;
    TIM6->ARR = 3972;           // this is for a 1-second period
    TIM6->PSC = 995;
    TIM6->CR1 |= TIM6_CR1_CEN;  // enable counting
}
:exmp.
:figcap.TIM6 initialization sample
:efig.
:h3.Enabling Interrupts
:p.At this point, TIM6 is active and counting... but it is 
:hp2.not:ehp2. generating interrupts! To achieve this, there is a bit 
we need to set in the :pk.TIM(6,7)->DIER:epk. 
:fn.DMA/Interrupt Enable Register
:efn.
register:
:fig width=column place=inline frame=rules.
:xmp.
/* TIM6 */
TIM6->DIER |= TIM_DIER_UIE;
NVIC_EnableIRQ(TIM6_IRQn);
NVIC_ClearPendingIRQ(TIM6_IRQn);
:exmp.
 
:figcap.TIM6 interrupt enablement example
:efig.
:h3.Timer ISR
:p.Last but not least, we need to write an :hp2.ISR:ehp2. 
:fn.Interrupt Service Routine
:efn.
for our TIM6 IRQ that we are now generating:
:fig width=column place=inline frame=rules.
:xmp.
void TIM6_IRQHandler() {
    // do something here...
    TIM6->SR &= ~TIM_SR_UIF;            // silence interrupt flag
    NVIC_ClearPendingIRQ(TIM6_IRQn);    // dismiss interrupt
}
:exmp.
 
:figcap.TIM6 interrupt enablement example
:efig.
:p.This function needs to be named specifically for the timer; if you 
were using TIM2, you would define the function as 
:pv.TIM2_IRQHandler:epv.! Likewise, this function does :hp1.two:ehp1. 
key things:
:ol.
:li.Dismiss the interrupt flag within the timer's :hp2.status register:ehp2.
:li.Dismiss the interrupt (or, more accurately, inform that processing 
of the ISR is complete) on the NVIC
:eol.
:lblbox.Taking Too Long!
:p.Something very important that some students will not take into 
account (especially on their final projects) is that any code within a 
timer ISR needs to :hp1.finish before the timer fires again!:ehp1. If 
you have a timer that triggers every 10 milliseconds, the code 
contained within that ISR's function body has to finish within 10 
milliseconds; failure to do this will result in the CPU being stuck 
processing the timer ISR forever!
:elblbox.
:h2 id=pwm.Using Timers for PWM
:p.:hp2.Pulse-width modulation:ehp2. is a trick wherein you vary the 
:hp5.duty cycle:ehp5. of a square wave to achieve various analog 
voltages. This can prove extremely useful for some control systems, 
including:
:ul.
:li.Motor speed
:li.LED brightness
:eul.
:p.PWM works by :hp1.subdividing the output voltage of a digital I/O 
pin:ehp1. by some percentage (the aforementioned duty cycle). PWM 
looks, practically, like this:
:fig width=column place=inline frame=rules.
:cgraphic.
50% duty cycle:
 
     &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.     &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.     &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
     &Lv.     &Lv.     &Lv.     &Lv.     &Lv.     &Lv.
     &Lv.     &Lv.     &Lv.     &Lv.     &Lv.     &Lv.
&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.     &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.     &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.     &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.
 
25% duty cycle:
 
     &Ul.&Lh.&Lh.&Ur.        &Ul.&Lh.&Lh.&Ur.        &Ul.&Lh.&Lh.&Ur.
     &Lv.  &Lv.        &Lv.  &Lv.        &Lv.  &Lv.
     &Lv.  &Lv.        &Lv.  &Lv.        &Lv.  &Lv.
&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.  &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.  &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.  &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.
:ecgraphic.
:figcap.PWM duty cycles
:efig.
:note.100% duty cycle would be flat DC, and 0% duty cycle would be no 
signal at all!
:p.The :hp2.period:ehp2. corresponds to the :hp5.width of the 
pulse:ehp5. and is not the same as the duty cycle. Here is the period 
and the duty cycle of a square wave:
:fig width=column place=inline frame=rules.
:cgraphic.
     &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.     &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.     &Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
     &Lv.     &Lv.     &Lv.     &Lv.     &Lv.     &Lv.
     &Lv.     &Lv.     &Lv.     &Lv.     &Lv.     &Lv.
&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.     &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.     &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.     &Ll.&Lh.&Lh.&Lh.&Lh.&Lh.
     &Lv.&Al.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ar.&Lv. Period - controlled by ARR
     &Lv.&Al.&Lh.&Lh.&Lh.&Ar.&Lv. Duty Cycle - controlled by CCR1
 
:ecgraphic.
:figcap.PWM period versus duty cycle
:efig.
:p.So, how does the output voltage derived from our PWM wave actually 
correlate to the duty cycle? Well, examine the handy input chart that 
follows. This is the :hp2.average voltage:ehp2. of the PWM waveform!
:note.The STM32 I/O pins have a logic :pk.1:epk. of :hp5.3.3 
volts:ehp5., so 100% duty cycle corresponds to exactly that.
:fig width=column place=inline frame=rules.
:artwork name=pwmvals.
:figcap.PWM and duty cycle relation plot
:efig.
:h3.Selecting a Timer
:p.First and foremost, :hp5.not all timers can be used for PWM!:ehp5. 
See the table :tref refid=timtbl. and note that :hp2.channel:ehp2. 
column -- if a timer has zero channels (like :pv.TIM6:epv. and 
:pv.TIM7:epv.), it :hp1.cannot:ehp1. be used for PWM! Likewise, we will 
demonstrate with :pv.TIM2:epv. (which can drive more than one PWM 
output at a time, but we will just be using one).
:p.For our example, we will use :pv.TIM2:epv., since it can output 
directly from the timer.
:h3 id=timpwm.Differences From the Basic Timers
:p.Unlike the basic timers (:pv.TIM6/7:epv., flip back to 
:hdref refid=timers. for information on those if you flipped here just 
for PWM), the PWM-capable timers require additional setup:
:ol.
:li.Enable the timer with the :pv.RCC->APB1ENR1:epv. register (see 
:tref refid=timenb. for the C statement to do this for :pv.TIM2:epv. or 
whichever timer you're using)
:li.Set the :pk.ARR:epk. and :pk.PSC:epk. registers to select the 
correct PWM frequency
:fn.Remember, the frequency will remain :hp5.constant:ehp5. :hp1.no 
matter what the duty cycle is!:ehp1. 
:efn.
:li.Enable the output channel with the :pk.CCMR1:epk. register
:li.Turn on the output for channel 1 with the :pk.CCER:epk. register
:li.Set the counter threshold value (equivalent to the :hp2.duty 
cycle:ehp2.) in the :pk.CCR1:epk. register
:li.Enable the interrupt by setting the :pv.URS:epv. flag in the 
:pk.CR1:epk. register
:li.Zero the counter by setting the :pv.UG:epv. flag in the 
:pk.EGR:epk. register
:li.Set both the :pv.CC1IE:epv. (channel 1 interrupt enable) and 
:pv.UIE:epv. flags in the :pk.DIER:epk. register
:li.Clear the :pv.CC1IF:epv. and :pv.UIF:epv. flags in the :pk.SR:epk. 
register
:li.Set the :pv.CEN:epv. flag of the :pk.CR1:epk. register to start 
counting
:eol.
:note.This list of tasks also enables :hp5.interrupts:ehp5. on 
:pv.TIM2:epv.; a version of code that won't enable interrupts will also 
be shown later!
:h3.CCR1 and the Duty Cycle
:p.The :pk.TIMx->CCR1:epk. register sets the :hp5.threshold:ehp5. that 
:pk.TIMx->CNT:epk. count-up register must reach before an :q.event:eq. 
occurs -- in our case, the event will:
:ol.
:li.Generate an interrupt
:li.Flip the output state of the PWM bit
:eol.
:p.Remember that the value you write to :pk.CCR1:epk. needs to be a 
:hp1.fraction:ehp1. of the value stored in :pk.ARR:epk.; the value in 
:pk.PSC:epk. is not considered and merely serves to alter the PWM 
frequency. A handy formula for computing the value is as follows:
:df align=center.
CCR1 = DC * ARR
:edf.
:p.Note that :f.DC:ef. is the duty cycle as a decimated percentage.  If 
you have a duty cycle number, like 1 through 10,
:fn.Where 1 is 10% and 10 is 100%
:efn.
you can use this formula instead:
:fig width=column place=inline frame=rules.
:df align=center.
CCR1 = <DC * ARR> over 10
:edf.
:p.The corresponding C statement would be:
:xmp.TIM2->CCR1 = (dutycycle * TIM2->ARR) / 10;
:exmp.
:figcap.CCR1 duty cycle formula
:efig.
:note.This does :hp1.integer division:ehp1. since we are not using any 
decimated numbers in either the numerator or denominator.
:h3.Picking the Output (or Input)
:p.The most difficult thing to do in this process is configuring the 
:pk.CCMR1:epk. register; the other register configurations are 
relatively simple and self-explained by the list under 
:hdref refid=timpwm.. However, this register is quite tough because it 
has :hp1.two:ehp1. modes, depending on whether or not the timer's 
channel is declared as :hp1.input capture mode:ehp1. 
:fn.This is the mode where you are counting based on pulses appearing 
on a GPIO pin.
:efn.
or :hp1.output compare mode.:ehp1. 
:fn.This is the mode where you are toggling a GPIO pin based on the 
result of a comparison operation performed against the counted value 
(with the counter being fed from a clock).
:efn.
:p.Depending on whether or not one of the channels is declared as an 
input or output, the layout of the register will :hp1.partially:ehp1. 
change. Here is the layout of the register for both input and output 
mode; we will then explore what these do:
:fig width=column place=inline frame=rules.
:cgraphic.
  7   6   5   4   3   2   1   0
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv.1F             &Lv.1PSC   &Lv.CC1S   &Lv.   Prefixed by "IC"
&Tr.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Tl.
&Lv. d &Lv. c &Lv. b &Lv. a &Lv. b &Lv. a &Lv. b &Lv. a &Lv.   Input Mode
&Ll.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lr.
 
 
  7   6   5   4   3   2   1   0
&Ul.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv.1CE&Lv.1M         &Lv.1PE&Lv.1FE&Lv.CC1S   &Lv.   Prefixed by "OC"
&Tr.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Ju.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Tl.
&Lv. a &Lv. c &Lv. b &Lv. a &Lv. a &Lv. a &Lv. b &Lv. a &Lv.   Output Mode
&Ll.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lr.
:ecgraphic.
:figcap.TIM2_CCMR1 input/output mode layout
:efig.
:p.So, as you can see, :pk.CC1S:epk. is constant between the two 
registers, and, while the register loops again for :pk.CC2S:epk. (see 
the manual for the STM32 you are using; head to :hdref refid=biblio. 
for the programming manual for your STM32), the mode selection 
double-bit will flip the rest of the register
:fn.Well, up until the second :pk.CC2S:epk. register appears!
:efn.
into its :q.alternate personality:eq. depending on what :pk.CC1S:epk. 
is set to:
:dl tsize=15.
:dthd.CC1S
:ddhd.Mode
:dt.:pk.00:epk. 
:dd.:pv.CC1:epv. is declared as an output
:dt.:pk.01:epk. 
:dd.:pv.CC1:epv. is connected to the :pk.TIM2_CH1:epk. GPIO alternate 
function
:dt.:pk.10:epk. 
:dd.:pv.CC1:epv. is connected to the :pk.TIM2_CH2:epk. GPIO alternate 
function
:dt.:pk.10:epk. 
:dd.:pv.CC1:epv. is connected to an internal trigger (this is not 
particularly useful)
:edl.
:p.Whenever you are in output mode, you will need to populate the 
:pk.OC1M:epk. bits (which are bits 4 through 6) to some specific 
pattern; for input mode, you will need to optionally set its prescaler 
(which is similar to the :pk.TIMx->PSC:epk. register, but another 
:q.layer:eq.), set the :hp1.filter:ehp1. (:pk.IC1F:epk.) to control how 
often sampling occurs given several clock pulses, and then start 
counting!
:h4 id=pwmin.Input Setup
:p.Setting up the input is relatively trivial; you only need to use 
code like this:
:fig width=column place=inline frame=rules.
:xmp.
RCC->APB1ENR1 |= RCC_APB1ENR1_TIM2EN;     // turn on TIM2 power
RCC->APB1ENR1 |= RCC_APB1ENR1_GPIOAEN;    // turn on GPIO PAx
 
// set PA0 to AF1 (TIM2_CH1)
GPIOA->MODER &= &tilde.0b11;
GPIOA->MODER |= 0b10;
GPIOA->AFR&lbrk.0&rbrk. &= &tilde.0b1111;
GPIOA->AFR&lbrk.0&rbrk. |= 0b0001;
 
// set the prescaler and autoreload register
TIM2->ARR = 0xFFFFFFFF;                   // maximum count value
TIM2->PSC = 0;                            // don't prescale
 
// put channel 1 into input mode and set it to input channel 1
TIM2->CCMR1 &= &tilde.TIM_CCMR1_CC1S;
TIM2->CCMR1 |= 0b01;                      // CC1S = input CH1
 
// count on the rising edge
TIM2->CCER &= &tilde.TIM_CCER_CC1P;
 
// turn on TIM2_IRQHandler() ISR interrupt generation
TIM2->DIER |= TIM_DIER_CC1IE;
NVIC_EnableIRQ(TIM2_IRQn);
 
// start counting
TIM2->CR1 |= TIM_CR1_CEN;
:exmp.
 
:figcap.TIM2 input setup with interrupt
:efig.
:h4.Output Setup
:p.While input mode is much easier to set up, output mode is something 
you need to master for 3040/3050 class!
:p.Output mode requires you to enter a specific bitmask into bits 4 
through 6 of :pk.TIM2->CCMR1:epk.. The bitmasks are as follows:
:table cols='1i *'.
:tcap.TIM2_CCMR1_OC1M Output Modes
:thd.
:c.:hp2.Bitmask:ehp2.
:c.:hp2.Description:ehp2.
:ethd.
:row split=yes.
:c.:pk.000:epk.
:c.Frozen; no events (interrupts or PWM pin flips) occur
:row split=yes.
:c.:pk.001:epk.
:c.Turn on channel 1 when :pk.TIM2->CNT:epk. equals
:pk.TIM2->CCR1:epk.
:row split=yes.
:c.:pk.010:epk.
:c.Turn off channel 1 when :pk.TIM2->CNT:epk. equals
:pk.TIM2->CCR1:epk.
:row split=yes.
:c.:pk.011:epk.
:c.Toggle channel 1 when :pk.TIM2->CNT:epk. equals
:pk.TIM2->CCR1:epk.
:row split=yes.
:c.:pk.100:epk.
:c.Keep channel 1 off
:row split=yes.
:c.:pk.101:epk.
:c.Keep channel 1 on
:row split=yes.
:c.:pk.110:epk.
:c.PWM mode 1; cause channel 1 to output as long as
:pk.TIM2->CNT:epk. is less than :pk.TIM2->CCR1:epk. (and
keep it from outputting when the reverse condition is true)
:row split=yes.
:c.:pk.111:epk.
:c.PWM mode 2; cause channel 1 to not output as long as
:pk.TIM2->CNT:epk. is less than :pk.TIM2->CCR1:epk. (and
output when the reverse condition is true)
:etable.
:p.For our PWM output, we want to set :pk.OC1M:epk. to :pk.110:epk. 
(or, :pk.TIM2->CCMR1:epk. should be set to :pk.01100000:epk.).
:note.For the :pk.ARR:epk. value, it needs to be set to whatever your 
desired count is :hp1.minus one.:ehp1. This is because the  register 
starts at 0!
:p.The following code block implements all of the requirements found in 
the list under :hdref refid=timpwm. in output mode:
:fig width=column place=inline frame=rules.
:xmp.
RCC->APB1ENR1 |= RCC_APB1ENR1_TIM2EN;     // turn on TIM2 power
RCC->APB1ENR1 |= RCC_APB1ENR1_GPIOAEN;    // turn on GPIO PAx
 
TIM2->ARR = 1000;                         // random values...
TIM2->PSC = 2;
 
// set PA0 to AF1 (TIM2_CH1)
GPIOA->MODER &= &tilde.0b11;
GPIOA->MODER |= 0b10;
GPIOA->AFR&lbrk.0&rbrk. &= &tilde.0b1111;
GPIOA->AFR&lbrk.0&rbrk. |= 0b0001;
 
// put channel 1 into output mode
TIM2->CCMR1 &= &tilde.TIM_CCMR1_CC1S;     // CC1S = output
 
// turn on preload mode on channel 1
TIM2->CCMR1 |= TIM_CCMR1_OC1PE;
 
// count on the rising edge
TIM2->CCER &= &tilde.TIM_CCER_CC1P;
 
// assign channel 0 as the output sink and use PWM mode 1
TIM2->CCMR1 |= 0b01100000;
 
// start counting
TIM2->CR1 |= TIM_CR1_CEN;
:exmp.
 
:figcap.TIM2 output setup
:efig.
:p.You can also write a version that generates interrupts:
:fig width=column place=inline frame=rules.
:xmp.
RCC->APB1ENR1 |= RCC_APB1ENR1_TIM2EN;     // turn on TIM2 power
RCC->APB1ENR1 |= RCC_APB1ENR1_GPIOAEN;    // turn on GPIO PAx
 
TIM2->ARR = 1000;                         // random values...
TIM2->PSC = 2;
 
// set PA0 to AF1 (TIM2_CH1)
GPIOA->MODER &= &tilde.0b11;
GPIOA->MODER |= 0b10;
GPIOA->AFR&lbrk.0&rbrk. &= &tilde.0b1111;
GPIOA->AFR&lbrk.0&rbrk. |= 0b0001;
 
// put channel 1 into output mode
TIM2->CCMR1 &= &tilde.TIM_CCMR1_CC1S;     // CC1S = output
 
// turn on preload mode on channel 1
TIM2->CCMR1 |= TIM_CCMR1_OC1PE;
 
// count on the rising edge
TIM2->CCER &= &tilde.TIM_CCER_CC1P;
 
// assign channel 0 as the output sink and use PWM mode 1
TIM2->CCMR1 |= 0b01100000;
 
// only make interrupts when the counter reaches its threshold
TIM2->CR1 |= TIM_CR1_URS;
 
// clear the counter in case it counted a bit
TIM2->EGR |= TIM_EGR_UG;
 
// assign the interrupt to channel 1 and enable interrupts
TIM2->DIER |= (TIM_DIER_CC1IE | TIM_DIER_UIE);
NVIC_EnableIRQ(TIM2_IRQn);
NVIC_ClearPendingIRQ(TIM2_IRQn);
 
// flush the interrupt flags
TIM2->SR &= ~(TIM_SR_CC1IF | TIM_SR_UIF);
 
// start counting
TIM2->CR1 |= TIM_CR1_CEN;
:exmp.
 
:figcap.TIM2 output setup with interrupts
:efig.
:h3.IRQ Handler
:p.If you enabled interrupts at all by using any of the above code, you 
will need to write an IRQ handler that looks like this:
:fig width=column place=inline frame=rules.
:xmp.
void TIM2_IRQHandler() {
    // do something here...
    TIM2->SR &= &tilde.TIM_SR_UIF;
    NVIC_ClearPendingIRQ(TIM2_IRQn);
}
:exmp.
 
:figcap.TIM2 IRQ handler code
:efig.
:h3 id=cpirq.About ClearPendingIRQ
:p.Whenever the ISR starts, the NVIC pending-interrupt bit will be 
cleared automatically. The reason the example ISRs above run 
:pk.NVIC_ClearPendingIRQ:epk. is because if for whatever reason an 
interrupt fires :hp1.during the ISR,:ehp1. you will have nested 
interrupts and you should dismiss the extra interrupts! 
:p.This is especially the case for timers, wherein if your timer ISR 
takes too long to run,
:fn.That is, if your code takes longer to run than your timer interrupt 
frequency!
:efn.
you may end up with a condition where you have far too many nested 
interrupts processing (and this leads to your program crashing).
:h1 id=adc.ADC
:p.Sometimes, you may wish to sample some kind of analog signal in real 
time. Some of these signals may include:
:ul.
:li.The speed of a motor
:li.The voltage of a battery or solar cell
:li.An audio or radio signal
:li.An analog sensor signal like a light sensor's output
:eul.
:p.This is what you would use an :hp2.analog-to-digital converter:ehp2. 
:i1.ADC
:h2.Understanding ADC Sampling
:p.The ADC functional block will take an input signal, sample it at 
specific times, and then quantize it to specific numeric values.
Generally speaking, there are two key parameters for a ADC:
:i2.Resolution (bit depth)
:ol.
:li.The :hp1.sampling rate:ehp1.
:li.The :hp1.bit depth:ehp1. 
:fn.The STM32 ADCs have a :hp2.12-bit:ehp2. depth by default, such that 
it can read values from 0 to 3.3 volts... corresponding to values from 
0 to 4095!
:efn.
-- also called the :hp2.resolution:ehp2. 
:eol.
:h3.Bit Depth
:p.The process of :hp1.quantization:ehp1. is technically 
:hp5.lossy:ehp5., and the following function describes the minimal 
distance in voltage between each possible ADC-reported value given an 
:hp1.n:ehp1.-bit ADC:
:i2.Quantization
:fig width=column place=inline frame=rules.
:df align=center.
V sub ref * <1 over <2 sup n>>
:edf.
 
:figcap.ADC quantization round-off voltage/step size
:efig.
:p.Knowing this, it may be helpful to see a chart showing a plot of a 
sine-wave function centered at 0 volts
:fn.Note something very important here: you would have to use 
:hp1.differential mode:ehp1. to sample this signal properly on the 
STM32; you would use :hp1.single-ended mode:ehp1. and add a DC bias to 
sample this when not using differential mode!
:efn.
and its corresponding sample value (given a 12-bit ADC):
:fig width=column place=inline frame=rules id=adcpic.
:artwork name=adcsin align=center.
:artwork name=adcsint align=center.
 
:figcap.ADC input function and output value relation
:efig.
:h3.Sampling Rate
:p.The sampling rate, :f.F:ef., of which the sampling period is :f.T = 
1 / F:ef., needs to be :hp5.double:ehp5. the maximum frequency you wish 
to sample -- this is the :hp2.Nyquist rate.:ehp2. Various digital audio 
systems over the years have used the following sample rates:
:ul.
:li.DVD and Blu-Ray audio tracks use 48 KHz
:li.Compact Discs use 44.1 KHz
:li.Digital telephone switches use 8 KHz
:eul.
:p.Likewise, various bit depths have been used in these systems (an 
earlier footnote notes that our STM32 has a 12-bit ADC depth):
:ul.
:li.DVD and Blu-Ray audio tracks use 16, 20, or 24-bit values
:li.CDs use signed 16-bit values
:li.Digital telephone switches use unsigned 8-bit values
:eul.
:h3.Our ADC Parameters
:p.Our STM32's ADC will use the following parameters, all of which can 
be changed (which we will explore next):
:dl tsize=15.
:dthd.Parameter
:ddhd.Value
:dt.Input Range
:dd.0 to 3.3 volts
:dt.Resolution
:dd.12 bits
:dt.Sample Rate
:dd.2.5 clock cycles, derived from SYSCLK
:fn.Remember, you learned about setting the SYSCLK input back in 
:hdref refid=clock.!
:efn.
:edl.
:h2.ADC Settings
:p.The STM32 ADC module is much more complicated than the timer 
modules. Not only can the ADC use :hp1.DMA:ehp1. to drop the sampled 
ADC value in lieu of dropping it into the ADC data register, it also 
has several :hp2.conversion modes!:ehp2. These are as follows:
:i2.Conversion mode
:ul.
:li.:hp2.Single,:ehp2. wherein you manually trigger the ADC to sample 
the inputs into one or more channels
:li.:hp2.Continuous,:ehp2. wherein the ADC will sample one or more 
channels over and over
:li.:hp2.Injected channel mode,:ehp2. wherein the ADC will run in 
continuous mode but will sample extra channels if certain external 
events occur
:eul.
:p.Likewise, there are two ways the ADC can return the captured values 
to your program:
:ul.
:li.When :hp2.DMA mode:ehp2. is enabled, each of the sampled ADC 
channels (which can be one or more) will be copied into your program's 
memory while the CPU is stalled
:fn.The DMA controller needs access to the CPU's main bus, so the CPU 
has to stall and yield control of the bus to the DMA controller 
temporarily; even then, this stalling action still results in faster 
memory copies than if the CPU were doing them in software!
:efn.
into an array of one or more channel values
:li.When DMA mode is disabled, each channel will be written 
back-to-back to the ADC data register, :pk.ADC_DR:epk..
:eul.
:lblbox.Multiple ADC Channels and No DMA
:p.If you are sampling multiple channels, you really are supposed to 
use DMA! The ADC DMA functions will output the 12-bit sampled values 
for each ADC channel into one or more 16-bit (:pv.unsigned short:epv. 
or :pv.uint16_t:epv.) variables in an array.
:p.Without DMA, each of the input channels will be sampled 
(:q.converted:eq.) and deposited into the same data register, 
back-to-back, and with such speed that it is effectively impossible to 
select any specific one value!
:p.Really, what DMA mode does is tell the DMA controller to copy out 
the value from the data register just before it is overwritten with the 
next inputted value.
:elblbox.
:h3 id=adcstp.Configuration Steps
:p.In order to actually configure an ADC, you would complete the 
following tasks:
:ol.
:li.Check the datasheet for your microcontroller to determine which 
GPIO pin corresponds to the input of each ADC's channel
:li.Set the GPIO pin(s) you wish to use for the input(s) to analog 
mode, which is :pk.11:epk. on the :pk.MODER:epk. bitmask
:li.Enable the ADCs by setting the :pk.RCC_AHB2ENR_ADCEN:epk. bit of 
the :pk.RCC->AHB2ENR:epk. register
:li.Clear the :pk.ADC_CR_DEEPPWD:epk. bit of the :pk.ADCx->CR:epk. 
register to turn off ADC deep power-down mode
:li.Wait a short while for the ADC to :q.wake up:eq. 
:fn.You certainly want to wait for the ADC to wake up; writing the 
other bits will :q.fall upon deaf ears:eq. when the ADC block is 
powered down!
:efn.
:li.Set the :pk.ADC_CR_ADVREGEN:epk. bit of the :pk.ADCx_CR:epk. 
register to turn on the voltage regulator (used to provide an accurate 
voltage reference for the sampling)
:li.Wait the same amount of time as before for the regulator to turn on
:li.Select the sampling mode by either setting (enabling) or clearing 
(disabling) the :pk.ADC_CFGR_CONT:epk. bit of the :pk.ADCx->CFGR:epk. 
register
:li.Select the overrun mode to either preserve the last good value or 
permit the ADC to read anyways by setting or clearing the 
:pk.ADC_CFGR_OVRMOD:epk. bit of the :pk.ADCx->CFGR:epk. register
:li.Set the :pk.RES&lbrk.1:0&rbrk.:epk. bits of the :pk.ADCx->CFGR:epk. 
register
:fn.These are bits 4 and 3 of the register!
:efn.
to one of the four values below:
:dl.
:dthd.Value
:ddhd.Resolution Bits
:dt.:pk.00:epk. 
:dd.12 bits
:dt.:pk.01:epk. 
:dd.10 bits
:dt.:pk.10:epk. 
:dd.8 bits
:dt.:pk.11:epk. 
:dd.6 bits
:edl.
:li.If using :hp2.DMA mode:ehp2., set the :pk.ADC_CFGR_DMACFG:epk. and 
:pk.ADC_CFGR_DMAEN:epk. bits of the :pk.ADCx->CFGR:epk. register 
:hp1.and also:ehp1. configure the DMA block
:fn.We will cover this later, flip to :hdref refid=adcdma.if you're 
curious right now!
:efn.
:li.Set the various parameters for the :q.regular sequences:eq. in the 
:pk.ADCx_SQRy:epk. registers where y is 0 to 3; set the :pk.SQ1:epk. to 
:pk.SQ4:epk. bits; read on to see what the layout of this register is 
and what the bit-setting does/selects
:li.Set the :pk.ADC_CR_ADEN:epk. bit of the :pk.ADCx_CR:epk. register
:li.Wait for the :pk.ADC_ISR_ADRDY:epk. bit of the :pk.ADCx->ISR:epk. 
register to set
:fn.C statement to do this: :pv.while(!(ADC1->ISR & 
ADC_ISR_ADRDY));:epv. 
:efn.
:li.Start conversion by setting the :pk.ADC_CR_ADSTART:epk. bit of the 
:pk.ADCx->CR:epk. register
:eol.
:h2.Programming the ADC
:p.This section will show you how to initialize the ADC and show you 
what the register layouts are. At the end, we will examine code samples 
that will do and don't use DMA mode!
:h3.ADC Input Channels
:p.Each ADC has :hp3.18:ehp3. input channels; the ones for 
:pk.ADC1:epk. are as follows for the NUCLEO-32 board:
:fn.For other STM32 boards, see the datasheets listed in 
:hdref refid=biblio.!
:efn.
:table cols='1i 3i'.
:tcap.ADC1 Inputs (STM32L432KCU)
:thd.
:c.Input
:c.GPIO Pin
:ethd.
:row split=yes.
:c.0
:c.Connected to the ADC voltage regulator
:row split=yes.
:c.1
:c.:hp1.Unavailable:ehp1.
:row split=yes.
:c.2
:c.:hp1.Unavailable:ehp1.
:row split=yes.
:c.3
:c.:hp1.Unavailable:ehp1.
:row split=yes.
:c.4
:c.:hp1.Unavailable:ehp1.
:row split=yes.
:c.5
:c.PA0
:row split=yes.
:c.6
:c.PA1
:row split=yes.
:c.7
:c.PA2
:row split=yes.
:c.8
:c.PA3
:row split=yes.
:c.9
:c.PA4
:row split=yes.
:c.10
:c.PA5
:row split=yes.
:c.11
:c.PA6
:row split=yes.
:c.12
:c.PA7
:row split=yes.
:c.13
:c.:hp1.Unavailable:ehp1.
:row split=yes.
:c.14
:c.:hp1.Unavailable:ehp1.
:row split=yes.
:c.15
:c.PB0
:row split=yes.
:c.16
:c.PB1
:etable.
:p.You will use this value later when you alter the sequence selection 
with the :pk.ADC1->SQR1:epk. register!
:h3.The ADC Configuration Registers
:p.We will need alter at least three registers in order to configure 
our ADC; we will use :pk.ADC1:epk. for our experiments.
:p.Check the :hp1.RM0394 Reference Manual:ehp1. (see 
:hdref refid=biblio. for this document) to see the layout of:
:ol.
:li.:pk.ADC_CR:epk.
:li.:pk.ADC_CFGR:epk.
:li.:pk.ADC_SQR1:epk. 
:eol.
:p.Here they are for the STM32L432KCU for your viewing convinence: 
:fig width=column place=inline frame=rules.
:cgraphic.
   31     30     29     28     27     26     25     24
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv. ADC  &Lv. ADCA &Lv. DEEP &Lv. ADVR &Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv.
&Lv. AL   &Lv. LDIF &Lv. PWD  &Lv. EGEN &Lv.      &Lv.      &Lv.      &Lv.      &Lv.
&Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
 
   23     22     21     20     19     18     17     16
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv.
&Lv.      &Lv.      &Lv.      &Lv.      &Lv.      &Lv.      &Lv.      &Lv.      &Lv.
&Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
 
   15     14     13     12     11     10      9      8
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv.
&Lv.      &Lv.      &Lv.      &Lv.      &Lv.      &Lv.      &Lv.      &Lv.      &Lv.
&Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
 
    7      6      5      4      3      2      1      0
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv. xxx  &Lv. xxx  &Lv. JAD  &Lv. AD   &Lv. JADS &Lv. ADST &Lv. AD   &Lv. AD   &Lv.
&Lv.      &Lv.      &Lv. STP  &Lv. STP  &Lv. TART &Lv. ART  &Lv. DIS  &Lv. EN   &Lv.
&Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
 
:ecgraphic.
:figcap.ADCx_CR layout
:efig.
:p.This is the ADC configuration register, :pk.ADC1->CFGR:epk.:
:fig width=column place=inline frame=rules.
:cgraphic.
   31     30     29     28     27     26     25     24
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv. JQ   &Lv. AWD1CH                           &Lv. J    &Lv. JAWD &Lv.
&Lv. DIS  &Lv.                                  &Lv. AUTO &Lv. 1EN  &Lv.
&Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
 
   23     22     21     20     19     18     17     16
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv. AWD  &Lv. AWD  &Lv. JQM  &Lv. JDIS &Lv. DISCNUM            &Lv. DISC &Lv.
&Lv. 1EN  &Lv. 1SGL &Lv.      &Lv. CEN  &Lv.                    &Lv. EN   &Lv.
&Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
 
   15     14     13     12     11     10      9      8
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ar.
&Lv. xxx  &Lv. AUT  &Lv. CONT &Lv. OVR  &Lv. EXTEN       &Lv. EXTSEL
&Lv.      &Lv. DLY  &Lv.      &Lv. MOD  &Lv.             &Lv.
&Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ar.
 
    7      6      5      4      3      2      1      0
&Al.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
              &Lv. ALI  &Lv. RES         &Lv. DFSD &Lv. DMA  &Lv. DMA  &Lv.
              &Lv. GN   &Lv.             &Lv. MCFG &Lv. CFG  &Lv. EN   &Lv.
&Al.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
 
:ecgraphic.
:figcap.ADCx_CFGR layout
:efig.
:note.There is a second configuration register, :pk.ADCx_CFGR2:epk., 
but we will not use it.
:p.The regular sequence register, :pk.ADC1->SQR1:epk., is the last 
important register:
:fig width=column place=inline frame=rules.
:cgraphic.
   31     30     29     28     27     26     25     24
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
&Lv. xxx  &Lv. xxx  &Lv. xxx  &Lv. SQ4                              &Lv.
&Lv.      &Lv.      &Lv.      &Lv.                                  &Lv.
&Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
 
   23     22     21     20     19     18     17     16
&Ul.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ar.
&Lv. xxx  &Lv. SQ3                              &Lv. xxx  &Lv. SQ2
&Lv.      &Lv.                                  &Lv.      &Lv.
&Ll.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ar.
 
   15     14     13     12     11     10      9      8
&Al.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ar.
                            &Lv. xxx  &Lv. SQ1
                            &Lv.      &Lv.
&Al.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ar.
 
    7      6      5      4      3      2      1      0
&Al.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Td.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Ur.
              &Lv. xxx  &Lv. xxx  &Lv. L                          &Lv.
              &Lv.      &Lv.      &Lv.                            &Lv.
&Al.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Tu.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lh.&Lr.
 
:ecgraphic.
:figcap.ADCx_SQR1 layout
:efig.
:h3.Using the ADC Without DMA
:p.We will use :pv.ADC1_IN6:epv. for our ADC input, which will mean our 
sequence length is equal to 1 and we will need to set PA1 to be analog 
mode. The following code provides an example of this:
:fig width=column place=inline frame=rules.
:xmp.
int waiting;
 
// turn on GPIO
RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
 
// set PA1 to analog mode
GPIOA->MODER |= 0b1100;
 
// turn on the ADC
RCC->AHB2ENR |= RCC_AHB2ENR_ADCEN;
 
// disable deep power-down mode and wait for the ADC to initialize
ADC1->CR &= &tilde.ADC_CR_DEEPPWD;
for(waiting = 0; waiting < 5000; waiting++);
 
// turn on the regulator and wait for it to stabilize
ADC1->CR |= ADC_CR_ADVREGEN;
for(waiting = 0; waiting < 5000; waiting++);
 
// enable continuous conversion mode
ADC1->CFGR |= ADC_CFGR_CONT;
 
// set ADC1->DR even if we overran the ADC input voltage limit
ADC1->CFGR |= ADC_CFGR_OVRMOD;
 
// clear the sequence length bits, then set the length to 1 (0x00)
ADC1->SQR1 &= &tilde.(0x0F);
ADC1->SQR1 |= 0x00;
 
// clear the bits for input 1, and assign it to ADC1_IN6 (0x180)
ADC1->SQR1 &= &tilde.(0x7C0);
ADC1->SQR1 |= (0x180);
 
// enable the ADC and wait for it to become ready
ADC1->CR |= ADC_CR_ADEN;
while(!(ADC1->ISR & ADC_ISR_ADRDY));
 
// start conversion
ADC1->CR |= ADC_CR_ADSTART;
:exmp.
:figcap.ADC non-DMA setup example
:efig.
:p.Carefully cross-correlate this with the list of steps shown in the 
list under :hdref refid=adcstp.!
:p.In order to actually read the ADC value, simply read the following 
register at any time in your program (or perhaps in a timer ISR):
:xmp.ADC1->DR
:exmp.
:p.Remember, this is a 16-bit register that only has 12 significant 
bits; see :figref refid=adcpic. to see the effect of sampling a sine 
wave that oscillates around 1.65 volts.
:fn.Why 1.65 volts? Well, the sine wave in that figure was shifted up 
with a DC offset such that its modulation would span about 2.6 volts 
down to 0.7 volts!
:efn.
:h3 id=adcdma.Using ADC DMA Mode
:p.This is a modified version of the previous example that uses the 
first DMA controller's 0th stream to copy the ADC data register, 
:pk.ADC1->DR:epk., to a variable in our program that we can read at any 
time. This example is split into two code blocks:
:ol.
:li.DMA initialization code
:li.ADC initialization code
:eol.
:fig width=column place=inline frame=rules.
:xmp keep=5.
uint16_t adc_buf;
 
// turn on DMA
RCC->AHB1ENR |= RCC_AHB1ENR_DMA1EN;
 
// set DMA1 channel 1 to ADC1
DMA1_CSELR->CSELR &= &tilde.DMA_CSELR_C1S;
 
// configure DMA1 channel 1 to do 16-bit transfers, increment
// the source (MINC) and destination (PINC) memory addresses as
// we go, turn on circular (CIRC) mode, and we want to transfer
// from the peripheral to the memory (so, DIR is 0)
DMA1_Channel1->CCR |= DMA_CCR_CIRC | DMA_CCR_MINC;
DMA1_Channel1->CCR &= &tilde.0b110000000000;
DMA1_Channel1->CCR |=  0b010000000000;       // this sets MSIZE
DMA1_Channel1->CCR &= &tilde.0b1100000000;
DMA1_Channel1->CCR |=  0b0100000000;         // this sets PSIZE
 
// set source and destination
DMA1_Channel1->CPAR = (uint32_t)&(ADC1->DR);
DMA1_Channel1->CMAR = (uint16_t)adc_buffer;  // re-typecast to 16-bit
 
// we want to transfer just one unsigned short at a time
DMA1_Channel1->CNDTR = 1;                    // one 16-bit item
:exmp.
:figcap.ADC + DMA setup example - DMA half
:efig.
:fig width=column place=inline frame=rules.
:xmp keep=5.
int waiting;
 
// turn on GPIO
RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
 
// set PA1 to analog mode
GPIOA->MODER |= 0b1100;
 
// power up ADC
RCC->AHB2ENR |= RCC_AHB2ENR_ADCEN;
 
// disable deep power-down mode and wait for the ADC to initialize
ADC1->CR &= &tilde.ADC_CR_DEEPPWD;
for(waiting = 0; waiting < 5000; waiting++);
 
// turn on the regulator and wait for it to stabilize
ADC1->CR |= ADC_CR_ADVREGEN;
for(waiting = 0; waiting < 5000; waiting++);
 
// enable continuous conversion mode
ADC1->CFGR |= ADC_CFGR_CONT;
 
// use DMA
ADC1->CFGR |= ADC_CFGR_DMAEN | ADC_CFGR_DMACFG;
 
// set ADC1->DR even if we overran the ADC input voltage limit
ADC1->CFGR |= ADC_CFGR_OVRMOD;
 
// clear the sequence length bits, then set the length to 1 (0x00)
ADC1->SQR1 &= &tilde.(0x0F);
ADC1->SQR1 |= 0x00;
 
// clear the bits for input 1, and assign it to ADC1_IN6 (0x180)
ADC1->SQR1 &= &tilde.(0x7C0);
ADC1->SQR1 |=  0x180;
 
// enable the ADC and wait for it to become ready
ADC1->CR |= ADC_CR_ADEN;
while(!(ADC1->ISR & ADC_ISR_ADRDY));
 
// start conversion
ADC1->CR |= ADC_CR_ADSTART;
:exmp.
:figcap.ADC + DMA setup example - ADC half 
:efig.
:p.Now, just like in the non-DMA example, you will have the ADC value 
crammed into the :pv.adc_buf:epv. buffer and only the first twelve bits 
will be significant!
:h1.Serial Communications 
:p.While none of this material is required in the ELEC 3040/3050 class, 
I am including this information in case you wish to use an STM32 in 
your Capstone project! 
:p.There are two serial interfaces that we will cover: 
:ol.
:li.:hp2.USART:ehp2. -- used for the commonplace :q.character 
displays:eq.,
:fn.These go by many names, but most of these feature 2 rows of 18 
characters; these are frequently used in Capstone projects! 
:efn.
communication with a computer, and more
:li.:hp2.SPI:ehp2. -- used for communication with serialized memory 
ICs, many types of sensors, and more
:eol.
:p.Let us learn how to configure the UART! 
:h2.USART 
:p.The :hp2.Universal Synchronous/Asynchronous 
Receiver/Transmitter,:ehp2. often called a :q.serial port,:eq. or a 
:q.COM port,:eq. 
:fn.Note that a COM port on the back of a PC or USB-to-serial adapter 
operates at :hp5.&pm.15 volts:ehp5. and will absolutely kill your STM32 
-- this UART connector type is called :hp2.RS232.:ehp2. 
:efn.
is a very common and simple way of (as discussed just above) 
communicating with PCs and input/output devices.
:i1.USART/UART 
:lblbox.USART or UART? 
:p.The STM32 UART controller has an :hp1.optional synchronous 
mode,:ehp1. wherein the controller provides an additional clock pin. 
:p.In asynchronous mode, you only use three pins: 
:ol.
:li.Ground 
:li.Receive 
:li.Transmit
:eol.
:p.Synchronous mode adds a :hp5.clock:ehp5. pin. 
:elblbox.
:h3.Computing the Baud Rate 
:p.Before you can send and receive anything, you have to determine what 
:hp2.baud rate:ehp2. you will be using! Here are some common baud 
rates: 
:table cols='1i'.
:tcap.Bauds
:row.
:c.300
:row.
:c.1200 
:row.
:c.2400 
:row.
:c.4800 
:row.
:c.9600 
:row.
:c.19200 
:row.
:c.38400 
:row.
:c.57600 
:row.
:c.115200 
:etable.
:p.For the following example, let's use :hp2.115200:ehp2. baud.
If our clock
:fn.This is :hp2.SYSCLK:ehp2. 
:efn.
defaults to 4 MHz, you can use the following formula to compute what 
the clock divider needs to be:  
:fig width=column place=inline frame=rules.
:df align=center.baud = <F sub CLK> over <divider>
:edf.
 
:figcap.USART clock divider formula
:efig.
:p.Simply algebraically rearrange the formula to solve for whichever 
value you need. So, if we enter 115200 baud as our baud rate and solve 
for the divider, we get a mantissa of 34 and a fraction of 72. 
:h3.Connecting the Pins 
:p.You will want to check the device datasheet (see 
:hdref refid=biblio.), and you will likely want to use :pv.USART1:epv.; 
as such, your transmit pin will be PA9 and your receive pin will be 
PA10. The alternate function for both of these will be AF7.
:fn.You will have to use the second indexing of the :pk.GPIOx->AFR:epk. 
register, so :pk.GPIOx->AFR&lbrk.1&rbrk.:epk..
:efn.
:h3.Send and Receive Functions 
:h3.Receive Interrupts 
:appendix.
:bibliog id=biblio.
:p.The following other books will be extensively useful in your studies:
:ul.
:li.:hp2.RM0394 Reference Manual:ehp2. -- for the following parts: 
STM32L41xxx, 42xxx, 43xxx, 44xxx, 45xxx, 46xxx
:p.STMicroelectronics. :hp1.R0394 Reference manual.:ehp1. ST Manuals, 
December 2024.
:li.:hp2.RM0090 Reference Manual:ehp2. -- for the following parts: 
STM32F405/415, STM32F407/417, STM32F427/437 and STM32F429/439
:p.STMicroelectronics. :hp1.R0090 Reference manual.:ehp1. ST Manuals, 
May 2026.
:li.:hp2.STM32L432KC Datasheet:ehp2.
:p.STMicroelectronics. :hp1.STM32L432KB, STM32L432KC.:ehp1. ST Manuals, 
May 2018.
:li.:hp2.STM32F411VE Datasheet:ehp2.
:p.STMicroelectronics. :hp1.STM32F411xC, STM32F411xE.:ehp1. ST Manuals, 
January 2024.
:li.:hp2.ELEC 2220 Textbook:ehp2.
:p.Zhu, Yifeng. :hp1.Embedded Systems with ARM Cortex-M in Assembly 
Language and C, 3rd Edition.:ehp1. E-Man Press, 2017.
:eul.
:h1 id=mxproj.Creating STM32CubeMX/IDE Projects
:p.Here is an outline of steps required to create an STM32 project.
:ol prefix='setup checkoff'.
:li.Create a directory
:fn.A :q.directory:eq. is a :hp5.folder:ehp5.; this term is more 
frequently heard amongst programmers!
:efn.
in one of the following locations:
:ul.
:li.The :pk.H:\:epk. drive
:li.A flash drive
:li.:hp3.NOT:ehp3. the root of the :pk.C:\:epk. drive!!
:eul.
:li.Open :hp2.STM32CubeMX:ehp2. from the Start menu.
:li.Click :rk.File:erk., then :rk.New Project...:erk.
:li.Several dialog boxes downloading files will appear, just let those 
run.
:li.In :q.Commercial Part Number:eq., enter the STM32 model:
:ul.
:li.:pk.STM32L432KCU6:epk., for the current 3040/3050 board (the 
:q.KC:eq. board)
:li.:pk.STM32L412KBU6:epk., for the older 3040/3050 board (the 
:q.KB:eq. board)
:li.:pk.STM32F411VET6:epk., for the 2200 board
:eul.
:li.Under the :pv.Part No:epv. header in the bottom half of the screen, 
click the part number that came up.
:li.Click :rk.Start Project:erk. at the top right.
:li.Click :rk.Project Manager:erk..
:li.In :hp2.Project Name:ehp2., enter a name of your choosing.
:li.In :hp2.Project Location:ehp2., click :rk.Browse:erk. and locate 
the directory you created in Step 1.
:note.If your path starts with something that looks like 
:pv.\\sage.eng.auburn.edu\:epv., you did not properly specify the 
directory you created.
:li.Make sure :hp2.Application Structure:ehp2. is set to 
:hp2.Advanced:ehp2..
:li.Change :hp2.Toolchain/IDE:ehp2. from :rk.EWARM:erk. 
to:rk.STM32CubeIDE:erk..
:li.Uncheck the checkbox to the left of :hp2.Use Default Firmware 
Location.:ehp2.
:li.In the :hp2.Firmware Relative Path:ehp2., click :rk.Browse:erk. and 
either type in or navigate to :pk.C:\Temp\STM32CubeFirmware:epk..
:note.If this step fails, re-check the box and continue to the next 
step; you'll have to wait a few minutes to download the firmware, 
though!
:li.Click :rk.Generate Code:erk. and wait for a while.
:li.Click :rk.Open Project:erk..
:li.STM32CubeIDE will open, permitting you to continue with the rest of 
your lab.
:eol.
:h1 id=fstring.Format Specifiers
:p.These are used in the :pk.printf:epk. and :pk.scanf:epk. family of C 
library functions; only :pk.scanf:epk. is available on the STM32 target 
C library in :pk.string.h:epk..
:table cols='1i 1i *'.
:tcap.Format Specifiers
:thd.
:c.:hp2.Specifier:ehp2.
:c.:hp2.Type:ehp2.
:c.:hp2.Description:ehp2.
:ethd.
:row split=yes.
:c.:pk.%d:epk. or :pk.%i:epk.
:c.:pk.int:epk.
:c.Signed decimal integer
:row split=yes.
:c.:pk.%u:epk.
:c.:pk.unsigned int:epk.
:c.Unsigned decimal integer
:row split=yes.
:c.:pk.%f:epk.
:c.:pk.float:epk.
:c.Decimal (floating-point)
:row split=yes.
:c.:pk.%lf:epk.
:c.:pk.double:epk.
:c.Long decimal (floating-point)
:row split=yes.
:c.:pk.%c:epk.
:c.:pk.char:epk.
:c.Single character
:row split=yes.
:c.:pk.%s:epk.
:c.:pk.char*:epk.
:c.Multiple characters (string)
:row split=yes.
:c.:pk.%p:epk.
:c.:pk.void*:epk.
:c.Memory address as hexadecimal
:row split=yes.
:c.:pk.%x:epk. or :pk.%X:epk.
:c.:pk.int:epk.
:c.Unsigned hexadecimal number (:pk.%X:epk. is uppercase)
:row split=yes.
:c.:pk.%o:epk.
:c.:pk.int:epk.
:c.Unsigned octal number
:row split=yes.
:c.:pk.%e:epk. or :pk.%E:epk.
:c.:pk.float/double:epk.
:c.Decimal in scientific notation
:row split=yes.
:c.:pk.%%:epk.
:c.:hp1.n/a:ehp1.
:c.Print a literal % character
:etable.
:h1 id=pnout.NUCLEO-L432KC Pinout 
:p.Feel free to photocopy this image as much as you'd like! 
:fig width=column place=inline frame=rules.
:artwork name=nucleo43 align=center width=p360.
 
:figcap.NUCLEO-L432KC Pinout
:efig.
:backm.
:glossary.
:p.Cross-references to other words that appear in the glossary are 
placed in :hp1.italic!:ehp1.
:gl.
:grpsep.A
:gt.Asynchronous
:gd.If an event is asynchronous, you can do other things while you wait 
for the event to complete. DMA is asynchronous.
:gt.ADC
:gd.Analog-to-Digital Converter. Samples an analog signal at specific 
times and converts it into a numeric representation. See 
:hdref refid=ADC. for more information!
:gt.AHB
:gd.Advanced High-performance Bus, the integrated data bus on the STM32 
that, like the :hp1.APB:ehp1., is hot-controllable.
:gt.APB
:gd.Advanced Peripheral Bus, the integrated bus on the STM32 that 
features peripherals that can be connected and disconnected from the 
CPU at will.
:gt.ARM
:gd.Advanced RISC Machine (originally Acorn RISC Machines, after the 
English computer company), the CPU architecture that the STM32 
implements.
:gt.ARR (Auto-reload register)
:gd.When you set the ARR register, a :hp1.counter:ehp1. will count up 
to this value and then generate an event. See :hdref refid=timers. for 
more information!
:grpsep.B
:gt.Baud rate 
:gd.The baud rate is the number of :hp1.bits per second:ehp1. 
transmitted on a serial link.
:gt.Bouncing
:gd.Unwanted jittering when a button is being pressed or released that 
may result in excessive interrupt generation or unstable control signal 
input.
:gt.Breakpoint
:gd.A specific memory address or line in a function that you wish for 
execution to stop on; these are implemented by the :hp1.debugger.:ehp1.
:grpsep.C
:gt.CAN
:gd.Controller Area Network. A multi-device bus-type network frequently 
used in automobiles and other such similar control systems.
:gt.Clock divider
:gd.A circuit (which, on the STM32, is configurable with 
the:pk.RCC:epk. register block) that divides the frequency of some 
master oscillator clock by some value to lower it.
:gt.Clock
:gd.A square-wave oscillator that clocks a sequential logic circuit, 
like a CPU.
:grpsep.D
:gt.DAC
:gd.Digital-to-Analog Converter. Takes a 12-bit decimal value and 
outputs a high-accuracy analog voltage.
:gt.Debounce
:gd.The act of removing multiple back-to-back button pressing events 
when a physical button is pressed (as the name implies, you have to 
remove "bouncing" from the button output signal)
:gt.Debugger
:gd.In the context of embedded systems, a debugger is a device that can 
stop and start the CPU, alter its memory, alter its flash, and possibly 
inspect CPU registers (and sometimes even peripheral registers).
:gt.Differential
:gd.If a signal is differential, it is carried on two wires; one 
carries positive values, and the other carries negative values. It is 
easier to interpret a signal that swings below ground level with 
differential signal pathways, and signals with a high chance of being 
lost in noise should always be carried differentially. See 
:hp1.single-ended.:ehp1.
:gt.DMA
:gd.Direct Memory Access. An additional component of the CPU can 
perform memory copying operations or peripheral driving operations 
asynchronously without the CPU intervening at all. The completion of a 
DMA event usually results in the generation of an interrupt.
:gt.Duty cycle
:gd.The percentage in which a square wave is turned "on", wherein a 50% 
duty cycle looks like a normal square wave.
:grpsep.E
:gt.EEPROM
:gd.Electronically-Erasable ROM, a block of memory on a microcontroller 
or discrete IC package that is intended to be written only a few times, 
but read far more times.
:gt.EXTI
:gd.External Interrupt. When a GPIO pin is allowed to flow to the CPU 
and generate an interrupt (by configuring the NVIC and EXTI register 
blocks), you are generating an EXTI event.
:grpsep.F
:gt.Flash
:gd.A type of :hp1.EEPROM:ehp1. that contains the stored program a 
microcontroller runs; some types of flash blocks on an STM32 can be 
used for user data.
:gt.Full-duplex
:gd.A serial interface that permits communication in both directions 
simultaneously. UART is full-duplex.
:grpsep.G
:gt.GPIO
:gd.General Purpose Input/Output, I/O pins that connect the 
microcontroller to the outside world.
:grpsep.H
:gt.Half-duplex
:gd.A serial interface that does not permit communication in both 
directions simultaneously. I&sup2.C is half-duplex.
:grpsep.I
:gt.Interrupt
:gd.A signal that pauses the CPU execution, saves the PC (program 
counter) register, runs a function, then restores the PC register and 
resumes normal execution. Interrupts are handled by ISRs.
:gt.I&sup2.C
:gd.Inter-Integrated Circuit, a low-speed serial device interface that 
requires only a clock and bidirectional data pin; this is a 
:hp1.half-duplex:ehp1. interface.
:gt.IRQ
:gd.Interrupt Request, an event that generates an interrupt.
:gt.ISR
:gd.Interrupt Service Routine, a function that the CPU jumps to 
whenever an interrupt fires.
:grpsep.L 
:gt.Level shifter 
:gd.This device converts the voltage levels of a serial communication 
interface, like RS232, to something palatable for a microcontroller's 
lower voltage levels.
:grpsep.N
:gt.NMI
:gd.Non-Maskable Interrupt, an interrupt that cannot be disabled and is 
usually triggered when the device malfunctions.
:gt.NVIC
:gd.Nested Vectored Interrupt Controller, the standard interrupt 
controller block found on :hp1.ARM Cortex-M:ehp1. series 
microcontroller CPUs.
:grpsep.P
:gt.Parallel 
:gd.Parallel communication involves sending all bits of a byte at the 
same time on at least 8 data pins at some specified :hp1.clock;:ehp1. 
the opposite of this is :hp1.serial:ehp1. resolution.
:gt.PC
:gd.Program Counter. This is the :hp1.register:ehp1. that holds the 
memory address of the currently-executing CPU instruction.
:gt.Prescaler
:gd.This is a type of :hp1.clock divider:ehp1. that controls the input 
clock frequency to a :hp1.timer.:ehp1.
:gt.PWM
:gd.Pulse-Width-Modulation. A simple way of getting a quasi-analog 
signal with a variable voltage from a bilevel (i.e. on or off) digital 
I/O pin by modulating the :hp1.duty cycle:ehp1. of the pin.
:grpsep.Q
:gt.Quantization
:gd.When you quantize a signal, you force it to certain pre-fixed 
values; this is similar to rounding wherein you might cut 3051.32 to 
3051 to allow a value to fit in a 12-bit register that can represent 
values ranging 0 to 4095.
:grpsep.R
:gt.RCC
:gd.Register and Clock Control, the control register that allows you to 
set the system clock source and other such things. This contains the 
:hp1.AHB:ehp1. and :hp1.APB:ehp1. control registers.
:gt.Resolution
:gd.The resolution of a sampled signal increases in accuracy with more 
bits; a formula that relates distortion, quantization loss, and bit 
depth to resolution can be written.
:gt.ROM
:gd.Read-Only Memory, a type of memory that usually contains the stored 
program a microcontroller or computer system runs.
:gt.Register
:gd.32-bit high-speed fields within the CPU that is the fundamental 
working storage for the CPU; see your notes from Computer Systems for 
more information.
:gt.RS232 
:gd.A physical serial port on a PC or terminal uses the RS232 
specification; the voltage levels switch between +15V and -15V to carry 
the data stream. You must use a :hp1.level shifter:ehp1. to connect 
this to a microcontroller.
:grpsep.S
:gt.Serial 
:gd.Serial communication involves sending each bit of a byte 
back-to-back at some pre-set :hp1.baud rate;:ehp1. the opposite of this 
is :hp1.parallel:ehp1. communication.
:gt.Single-ended
:gd.If a signal is single-ended, it is carried on one wire and is also 
more susceptible to noise. See :hp1.differential.:ehp1.
:gt.SPI
:gd.Serial Peripheral Interface. Many peripherals use SPI, ranging from 
ultrasonic range sensors, some microphones, RAM and ROM chips, SD 
cards, some character displays, and other devices of this nature.
:gt.ST-LINK
:gd.The :hp1.debugger:ehp1. included on STM32 development boards. If 
you are designing your own STM32-based board, you will need to either 
get an external ST-LINK box or add the chip directly onto your board.
:gt.STMicroelectronics
:gd.The company that made the STM32 microcontroller.
:gt.SVC
:gd.Supervisor Call, an interrupt that a user program will generate 
using a software interrupt generation CPU instruction that jumps into 
the operating system (the "supervisor") to handle a system call.
:gt.Synchronous
:gd.If an event is synchronous, you must wait for it to finish before 
you can move onto the next event.
:gt.SysTick
:gd.A special interrupt generated by an integral timer derived stably 
from the oscillator that provides the CPU clock. Used for the scheduler 
jiffy clock of an operating system or any number of tasks wherein you 
might need an event that fires repeatedly.
:grpsep.U
:gt.UART
:gd.Universal Asynchronous Receiver/Transmitter, the standard serial 
interface found on PCs and all manner of communication devices.
Sometimes, it may be :hp5.synchronous:ehp5., wherein it becomes a 
:hp2.USART:ehp2. (which is what the STM32 has).
:gt.USART
:gd.See UART.
:grpsep.V
:gt.vtable
:gd.A colloquial name for an array of function pointers.
:egl.
:index.
:euserdoc.
